---
ID: "4f0d5da2-bf93-4f3e-a874-1fa1a791b20f"
Parent: "de7eca5e-86fe-4d0b-b5c5-96a03c7bc279"
Template: "de7eca5e-86fe-4d0b-b5c5-96a03c7bc279"
Path: /sitecore/templates/Project/HCA/Consultant finder/Frames/CMADisclosures/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250206T120149Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6b6c1ca8-aa7c-4004-b1b3-fc6fe1c4a00e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250206T120149Z
