---
ID: "895900a3-2f26-437c-8bbd-795faa72727f"
Parent: "8cc2ce39-6843-42fd-b9f2-dc78f5217e57"
Template: "8cc2ce39-6843-42fd-b9f2-dc78f5217e57"
Path: /sitecore/templates/Project/HCA/Consultant finder/Steps/StepTermsAndConditions/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250206T120149Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b49ae80b-0b31-43bd-b452-3ec4cb36959c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250206T120149Z
