---
ID: "d9728ab7-e105-4e7e-b40a-570b8cc0220b"
Parent: "65e1b98c-3aaf-474b-9bad-f136c7b9c5b0"
Template: "65e1b98c-3aaf-474b-9bad-f136c7b9c5b0"
Path: /sitecore/templates/Project/HCA/Page Content/Locations Search Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {B7DD721A-C2D4-4907-BA35-0BAF272D7F9A}
    {65E1B98C-3AAF-474B-9BAD-F136C7B9C5B0}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e2b25fda-d65a-403d-83bb-c1dd05eb70c3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\carmen.popovici@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240301T120940Z
