---
ID: "41ecc472-c3a2-4bbb-8b76-b600326d8e68"
Parent: "b75b574f-ab3f-46ef-9ec0-abd289fa4f23"
Template: "b75b574f-ab3f-46ef-9ec0-abd289fa4f23"
Path: /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/OpenGraph Metadata Params/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6e5cb33a-412a-4886-9193-51f1bce2f86d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\carmen.popovici@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240327T084458Z
