---
ID: "3b1c2c44-35d0-43e3-bab2-1cb6b989ba3b"
Parent: "31bed162-819a-435f-8d1f-6b30cf400b85"
Template: "31bed162-819a-435f-8d1f-6b30cf400b85"
Path: /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Header With Image/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4462c915-f664-45d4-9a4b-41ab20e87dc3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\carmen.popovici@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231230T220010Z
