---
ID: "d625e877-013b-4ffe-b75c-9f2f92778e7c"
Parent: "d06abdf9-f642-4bf4-a010-81d074f46c5a"
Template: "d06abdf9-f642-4bf4-a010-81d074f46c5a"
Path: /sitecore/templates/Project/HCA/Navigation/Table of contents/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241128T151727Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7ca0fb29-da07-4a76-8b00-3eadc7fa612f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "bf8e7050-a036-495e-97e6-455933fb6424"
      Hint: Title
      Value: Jump to
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250123T110101Z
