---
ID: "dc548674-b433-456c-b760-c6e110fd5866"
Parent: "6d1ace35-819d-4515-a86d-89ab96696f61"
Template: "6d1ace35-819d-4515-a86d-89ab96696f61"
Path: /sitecore/templates/Project/HCA/Page Content/Call Us Today CTA/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240402T161048Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7ac8c868-b269-484a-baf8-888d6fc2c905"
    - ID: "abedf982-8d06-4980-bc29-dc6822c9843e"
      Hint: CTAText
      Value: Call us <strong>today</strong>
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240402T161158Z
    - ID: "fa0ec83d-c7c7-4d1b-8307-97c25471b2a9"
      Hint: CTAIcon
      Value: "{8B8CC93B-F778-4E08-954A-FA67D54E5B04}"
