import { createContext, useEffect, useState } from 'react';
import axios from 'axios';

export const IvfCalculatorContext = createContext();

const IvfCalculatorContextProvider = ({ children }) => {
  const [costData, setCostData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [errorData, setErrorData] = useState(false);
  // selections variables
  const [cycleTypeVal, setCycleTypeVal] = useState('');
  const [protocolType, setProtocolType] = useState('');
  const [stimulationDrug, setStimulationDrug] = useState('');
  const [startingDose, setStartingDose] = useState('');
  const [blastocystCulture, setBlastocystCulture] = useState('');
  const [adjuvants, setAdjuvants] = useState([]);
  const [adjuvantsValuesPrint, setAdjuvantsValuesPrint] = useState([]);
  const [selectedDrugValue, setSelectedDrugValue] = useState('');
  // helpers variables
  const [isDisabled, setIsDisabled] = useState(true);
  const [totalCost, setTotalCost] = useState(0);
  // conditional variables to show fields
  const [isProtocolType, setIsProtocolType] = useState(false);
  const [isStartingDrug, setIsStartingDrug] = useState(false);
  const [isStimulationDrug, setIsStimulationDrug] = useState(false);
  const [isBlastocyst, setIsBlastocyst] = useState(false);
  const [isAdjuvants, setIsAdjuvants] = useState(false);
  // eslint-disable-next-line
  const [error, setError] = useState('');
  const [isCalculating, setIsCalculating] = useState(false);
  const [checkStatus, setCheckStatus] = useState([]);
  // costs variables
  const [cycleTypeCost, setCycleTypeCost] = useState(0);
  const [cycleCost, setCycleCost] = useState(0);
  const [protocolTypeCost, setProtocolTypeCost] = useState(0);
  const [blastocystCultureCost, setBlastocystCultureCost] = useState(0);
  const [adjuvantsCost, setAdjuvantsCost] = useState(0);
  // notes variables
  const [protocolNotes, setProtocolNotes] = useState('');
  const [cycleNotes, setCycleNotes] = useState('');
  const [cycleTypeAdditionalDrugNotes, setCycleTypeAdditionalDrugNotes] =
    useState('');
  const [blastocystCultureNotes, setBlastocystCultureNotes] = useState('');
  const [startingDoseNotes, setStartingDoseNotes] = useState('');
  const [adjuvantsNotes, setAdjuvantsNotes] = useState(0);
  const [selectedDrugNotes, setSelectedDrugNotes] = useState('');
  const [introPDF, setIntroPDF] = useState('');
  // calculator heading
  const [calculatorHeading, setCalculatorHeading] = useState('');
  // labels
  const [cycleTypeLabel, setCycleTypeLabel] = useState('');
  const [blastocystCultureLabel, setBlastocystCultureLabel] = useState('');
  const [startingDoseLabel, setStartingDoseLabel] = useState('');
  const [protocolTypeLabel, setProtocolTypeLabel] = useState('');
  const [stimulationDrugLabel, setStimulationDrugLabel] = useState('');
  const [adjuvantsLabel, setAdjuvantsLabel] = useState('');
  const [drugPriceLabel, setDrugPriceLabel] = useState('');
  const [calculateButtonLabel, setCalculateButtonLabel] = useState('');

  // change host based on enviroment variable
  /*   let urlHost;
  if (process.env.NODE_ENV === 'production') {
    urlHost = window.location.origin;
  } else {
    urlHost = 'https://forms.hcahealthcare.co.uk';
  } */

  const urlHost = '';

  // TODO create a new web service to serve the excel data
  //https://forms.hcahealthcare.co.uk/lookupApi/IVFCostCalculator/default/findbydictionaryasobject/Costs
  const costDataMock = {
    Title: {
      Title: {
        Value: 'Title',
        Order: '0',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: "Let's get started",
        AdditionalDrugNotes: null,
        Label: 'Title',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
    },
    CalculatorHeading: {
      CalculatorHeading: {
        Value: 'CalculatorHeading',
        Order: '1',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes:
          'Use our cost calculator to get a personalised costed treatment plan',
        AdditionalDrugNotes: null,
        Label: 'CalculatorHeading',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
    },
    Image: {
      CalculatorImage: {
        Value: '/static/legacy/assets/images/IVFCalcPreCalc.jpg',
        Order: '2',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Calculator Image',
        AdditionalDrugNotes: null,
        Label: 'Calculator Image',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      HCALogoPDF2x: {
        Value: '/static/legacy/assets/images/HCAListerLogoPDF2x.jpg',
        Order: '3',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'HCA Logo PDF Image',
        AdditionalDrugNotes: null,
        Label: 'HCA Logo PDF Image',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
    },
    Introduction: {
      Introduction: {
        Value: 'Introduction',
        Order: '4',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes:
          'Each patient journey is unique and our pricing is tailored to your treatment plan as discussed with your clinician. The cost provided is an estimate and is subject to changes including the below factors or additional measures that may be identified during your treatment. Pre-treatment investigation costs are as outlined in our price list. The fees quoted are only applicable if you are self-funding.  If you have fertility benefit with AXA PPP, Bupa or Vitality and they have approved cover then the fees will be billed in line with the agreed contracted rates.  Your insurance company or patient accounts will be able to advise further. Recommendations will be discussed with you and will only be raised if clinically necessary and with the aim to maximise success rate or safety.',
        AdditionalDrugNotes: null,
        Label: 'Introduction',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
    },
    FullText: {
      FullTextMarkup: {
        Value: 'FullText',
        Order: '5',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes:
          "<div class='ivf-calculator__small-print-item'><h3>Monitoring Bloods</h3><p>These costs are based on the average number of monitoring bloods of 4 per cycle and the type of test required will depend on the protocol being undertaken (estradiol alone if Long protocol / Full monitoring profile if Antagonist protocol) so this may vary if more or less tests are required depending on duration of stimulation.</p></div><div class='ivf-calculator__small-print-item'><h3>Medication</h3><p>Costs are based on a typical 12 day duration of stimulation (but this may vary as may the dose through the cycle), standard ovitrelle trigger and use of cylogest alone to pregnancy test day.\n\nSupplementary medication may occasional be required that is not included. We recommend purchasing medication from our pharmacy that is competitively priced either in person or via our courier service for ease and peace of mind but there is no obligation to do so.A further cost of medications per cycle will be required for those achieving a pregnancy until 12 weeks which is typically cyclogest alone (but this may vary) at total cost of £202.16 for those 8 weeks.</p></div><div class='ivf-calculator__small-print-item'><h3>Advanced Embryology</h3><p>This includes Embryoscope used in all cycle and embryo glue where applicable. Blastocyst Culture to Day 5 and the use of AI to enhance embryo choice will be routinely recommended if there are a sufficient number of embryos on Day 3 as further culture will enhance embryo selection for transfer. There will be a 500 refund of the advanced embryology fee if embryos are not cultured beyond Day 3. This will not apply if embryos are cultured beyond Day 3 but no blastocysts are available for transfer or freeze.</p></div><div class='ivf-calculator__small-print-item'><h3>Fertilisation Method</h3><p>On occasion ICSI may be recommended on the day of egg collection when not previously planned due to suboptimal semen parameters and this will incur an additional cost of £1390.</p></div><div class='ivf-calculator__small-print-item'><h3>PGT-A</h3><p>This is costed for 2 embryos available for biopsy at £500/embryo along with the £500 PGT-A set-up fee.\nThis final cost will therefore depend on the number of embryos for testing.</p></div><div class='ivf-calculator__small-print-item'><h3>Embryo Freezing</h3><p>If a freeze-all is decided upon rather than transfer there will be no charge for embryo freezing. A subsequent frozen cycle fee of £2350 will apply. If a fresh transfer occurs and there are supernumerary embryos available to freeze, a £940 fee will apply.</p></div>",
        AdditionalDrugNotes: null,
        Label: 'FullText',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
    },
    SummaryLabel: {
      Heading: {
        Value: 'IVF Cost Estimation',
        Order: '6',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'IVF Cost Estimation',
        AdditionalDrugNotes: null,
        Label: 'IVF Cost Estimation',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      CycleCost: {
        Value: 'Cycle cost',
        Order: '7',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Cycle cost',
        AdditionalDrugNotes: null,
        Label: 'Cycle cost',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      ProtocolCost: {
        Value: 'Monitoring blood cost',
        Order: '8',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Monitoring blood cost',
        AdditionalDrugNotes: null,
        Label: 'Monitoring blood cost',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      BlastocystCultureCost: {
        Value: 'Advanced embryology cost',
        Order: '9',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Advanced embryology cost',
        AdditionalDrugNotes: null,
        Label: 'Advanced embryology cost',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      CycleDrugCost: {
        Value: 'Cycle drug cost',
        Order: '10',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Cycle drug cost',
        AdditionalDrugNotes: null,
        Label: 'Cycle drug cost',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      AdjuvantsCost: {
        Value: 'Adjuvants cost',
        Order: '11',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Adjuvants cost',
        AdditionalDrugNotes: null,
        Label: 'Adjuvants cost',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
    },
    Label: {
      CycleType: {
        Value: 'Cycle type',
        Order: '12',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Cycle type',
        AdditionalDrugNotes: null,
        Label: 'Cycle type',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      ProtocolType: {
        Value: 'Protocol type',
        Order: '13',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Protocol type',
        AdditionalDrugNotes: null,
        Label: 'Protocol type',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      StimulationDrug: {
        Value: 'Stimulation drug',
        Order: '14',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Stimulation drug',
        AdditionalDrugNotes: null,
        Label: 'Stimulation drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      StartingDose: {
        Value: 'Starting dose',
        Order: '15',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Starting dose',
        AdditionalDrugNotes: null,
        Label: 'Starting dose',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      BlastocystCulture: {
        Value: 'Advanced Embryology',
        Order: '16',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Advanced Embryology',
        AdditionalDrugNotes: null,
        Label: 'Advanced Embryology',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      Adjuvants: {
        Value: 'Adjuvants',
        Order: '17',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Adjuvants',
        AdditionalDrugNotes: null,
        Label: 'Adjuvants',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      CycleDrug: {
        Value: 'Cycle drug',
        Order: '18',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Cycle drug',
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      CalculateButton: {
        Value: 'Calculate',
        Order: '35',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Calculate',
        AdditionalDrugNotes: null,
        Label: 'Calculate',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      DownloadPDFButton: {
        Value: 'Download as a PDF',
        Order: '36',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Download as a PDF',
        AdditionalDrugNotes: null,
        Label: 'Download as a PDF',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      ResetButton: {
        Value: 'Reset',
        Order: '37',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Reset',
        AdditionalDrugNotes: null,
        Label: 'Reset',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      AdjuvantsText: {
        Value: 'Text',
        Order: '38',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes:
          'For more information on indication, evidence base and HFEA traffic light rating for any adjuvants recommended please see ',
        AdditionalDrugNotes: null,
        Label:
          'For more information on indication, evidence base and HFEA traffic light rating for any adjuvants recommended please see ',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      AdjuvantsLink: {
        Value: 'Link',
        Order: '39',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes:
          'https://forms.hcahealthcare.co.uk/-/media/ivf-calc/pdfs/fertility-treatment-adjuvants-24.pdf',
        AdditionalDrugNotes: null,
        Label:
          'https://forms.hcahealthcare.co.uk/-/media/ivf-calc/pdfs/fertility-treatment-adjuvants-24.pdf',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
    },
    PDFLabel: {
      PDFTableHeading: {
        Value: 'IVF Cost Estimation',
        Order: '19',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'IVF Cost Estimation',
        AdditionalDrugNotes: null,
        Label: 'IVF Cost Estimation',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PDFTableColumn1Heading: {
        Value: 'Item',
        Order: '20',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Item',
        AdditionalDrugNotes: null,
        Label: 'Item',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PDFTableColumn2Heading: {
        Value: 'Selection',
        Order: '21',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Selection',
        AdditionalDrugNotes: null,
        Label: 'Selection',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PDFTableColumn3Heading: {
        Value: 'Cost',
        Order: '22',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Cost',
        AdditionalDrugNotes: null,
        Label: 'Cost',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PDFTableColumn4Heading: {
        Value: 'Note',
        Order: '23',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Note',
        AdditionalDrugNotes: null,
        Label: 'Note',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PDFTableItem1Heading: {
        Value: 'Cycle Type',
        Order: '24',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Cycle Type',
        AdditionalDrugNotes: null,
        Label: 'Cycle Type',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PDFTableItem2Heading: {
        Value: 'Protocol Monitoring Bloods cost',
        Order: '25',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Protocol Monitoring Bloods cost',
        AdditionalDrugNotes: null,
        Label: 'Protocol Monitoring Bloods cost',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PDFTableItem3Heading: {
        Value: 'Advanced Embryology',
        Order: '26',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Advanced Embryology',
        AdditionalDrugNotes: null,
        Label: 'Advanced Embryology',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PDFTableItem4Heading: {
        Value: 'Adjuvants',
        Order: '27',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Adjuvants',
        AdditionalDrugNotes: null,
        Label: 'Adjuvants',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PDFTableItem5Heading: {
        Value: 'Cycle drug',
        Order: '28',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Cycle drug',
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PDFTableItemTotalCostHeading: {
        Value: 'Total cost (estimate)',
        Order: '29',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Total cost (estimate)',
        AdditionalDrugNotes: null,
        Label: 'Total cost (estimate)',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
    },
    PDFContent: {
      PDFWhatHappensNextHeading: {
        Value: 'What happens next?',
        Order: '30',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'What happens next?',
        AdditionalDrugNotes: null,
        Label: 'What happens next?',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PDFWhatHappensNextBody: {
        Value: 'To book a follow up consultation contact us on',
        Order: '31',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'To book a follow up consultation contact us on',
        AdditionalDrugNotes: null,
        Label: 'To book a follow up consultation contact us on',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PDFWhatHappensNextPhoneNumber: {
        Value: '0234 556 876',
        Order: '32',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: '020 7079 4344',
        AdditionalDrugNotes: null,
        Label: '020 7079 4344',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PDFFurtherInformationHeading: {
        Value: 'Further Information',
        Order: '33',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: 'Further Information',
        AdditionalDrugNotes: null,
        Label: 'Further Information',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PDFFurtherInformationBody: {
        Value: null,
        Order: '34',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: null,
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
    },
    CycleType: {
      IVF: {
        Value: 'IVF',
        Order: '100',
        Cost: '3995',
        AdditionalDrugCost: '0',
        Notes:
          'On occasion ICSI may be recommended on the day of egg collection when not previously planned due to suboptimal semen parameters and this will incur an additional cost of £1390.\nIf a freeze-all is decided upon rather than transfer there will be no charge for embryo freezing. A subsequent frozen cycle fee of £2350 will apply. If a fresh transfer occurs and there are supernumerary embryos available to freeze, a £940 fee will apply.',
        AdditionalDrugNotes:
          'A further cost of medications per cycle will be required for those achieving a pregnancy until 12 weeks which is typically cyclogest alone (but this may vary) at total cost of £202.16 for those 8 weeks.',
        Label: 'Cycle type',
        Cost1: '3950',
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      ICSI: {
        Value: 'ICSI',
        Order: '101',
        Cost: '5385',
        AdditionalDrugCost: '0',
        Notes:
          'If a freeze-all is decided upon rather than transfer there will be no charge for embryo freezing. A subsequent frozen cycle fee of £2350 will apply. If a fresh transfer occurs and there are supernumerary embryos available to freeze, a £940 fee will apply.',
        AdditionalDrugNotes:
          'A further cost of medications per cycle will be required for those achieving a pregnancy until 12 weeks which is typically cyclogest alone (but this may vary) at total cost of £202.16 for those 8 weeks.',
        Label: 'Cycle type',
        Cost1: '3950',
        Cost1Type: null,
        Cost2: '1390',
        Cost2Type: null,
      },
      IMSI: {
        Value: 'IMSI',
        Order: '102',
        Cost: '5859',
        AdditionalDrugCost: '0',
        Notes:
          'If a freeze-all is decided upon rather than transfer there will be no charge for embryo freezing. A subsequent frozen cycle fee of £2350 will apply. If a fresh transfer occurs and there are supernumerary embryos available to freeze, a £940 fee will apply.',
        AdditionalDrugNotes:
          'A further cost of medications per cycle will be required for those achieving a pregnancy until 12 weeks which is typically cyclogest alone (but this may vary) at total cost of £202.16 for those 8 weeks.',
        Label: 'Cycle type',
        Cost1: '3950',
        Cost1Type: null,
        Cost2: '1855',
        Cost2Type: null,
      },
      EggFreezing: {
        Value: 'Egg Freezing',
        Order: '103',
        Cost: '3790',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle type',
        Cost1: '3750',
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      EggThaw: {
        Value: 'Egg Thaw',
        Order: '104',
        Cost: '3740',
        AdditionalDrugCost: '0',
        Notes:
          'If a freeze-all is decided upon rather than transfer there will be no charge for embryo freezing. A subsequent frozen cycle fee of £2350 will apply. If a fresh transfer occurs and there are supernumerary embryos available to freeze, a £940 fee will apply.',
        AdditionalDrugNotes:
          'A further cost of medications per cycle will be required for those achieving a pregnancy until 12 weeks which is typically cyclogest alone (but this may vary) at total cost of £202.16 for those 8 weeks.',
        Label: 'Cycle type',
        Cost1: '3340',
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      EmbryoThaw: {
        Value: 'Embryo Thaw',
        Order: '105',
        Cost: '2350',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes:
          'A further cost of medications per cycle will be required for those achieving a pregnancy until 12 weeks which is typically cyclogest alone (but this may vary) at total cost of £202.16 for those 8 weeks.',
        Label: 'Cycle type',
        Cost1: '1950',
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
    },
    ProtocolType: {
      Long: {
        Value: 'Long',
        Order: '106',
        Cost: '315',
        AdditionalDrugCost: '0',
        Notes:
          'These costs are based on the average number of monitoring bloods of 4 per cycle and the type of test required will depend on the protocol being undertaken (estradiol alone if Long protocol / Full monitoring profile if Antagonist protocol) so this may vary if more or less tests are required depending on duration of stimulation.',
        AdditionalDrugNotes: null,
        Label: 'Protocol type',
        Cost1: '290',
        Cost1Type: 'average monitoring blood cost',
        Cost2: null,
        Cost2Type: null,
      },
      Antagonist: {
        Value: 'Antagonist',
        Order: '107',
        Cost: '660',
        AdditionalDrugCost: '0',
        Notes:
          'These costs are based on the average number of monitoring bloods of 4 per cycle and the type of test required will depend on the protocol being undertaken (estradiol alone if Long protocol / Full monitoring profile if Antagonist protocol) so this may vary if more or less tests are required depending on duration of stimulation.',
        AdditionalDrugNotes: null,
        Label: 'Protocol type',
        Cost1: '612',
        Cost1Type: 'average monitoring blood cost',
        Cost2: null,
        Cost2Type: null,
      },
      NaturalThawCycle: {
        Value: 'Natural Thaw Cycle',
        Order: '108',
        Cost: '0',
        AdditionalDrugCost: '90',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Protocol type',
        Cost1: '0',
        Cost1Type: 'monitoring blood cost',
        Cost2: '0',
        Cost2Type: 'monitoring blood cost',
      },
      MedicatedThawCycle: {
        Value: 'Medicated Thaw Cycle',
        Order: '109',
        Cost: '60',
        AdditionalDrugCost: '150',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Protocol type',
        Cost1: '0',
        Cost1Type: 'monitoring blood cost',
        Cost2: '55',
        Cost2Type: 'monitoring blood cost',
      },
    },
    StimulationDrug: {
      Menopur: {
        Value: 'Menopur',
        Order: '110',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Stimulation drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      GonalF: {
        Value: 'Gonal F',
        Order: '111',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Stimulation drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      Meriofert: {
        Value: 'Meriofert',
        Order: '112',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Stimulation drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      Fostimon: {
        Value: 'Fostimon',
        Order: '113',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Stimulation drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      Pergoveris: {
        Value: 'Pergoveris',
        Order: '114',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Stimulation drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
    },
    StartingDose: {
      _150: {
        Value: '150',
        Order: '117',
        Cost: null,
        AdditionalDrugCost: '0',
        Notes:
          'Costs are based on a typical 12 day duration of stimulation (but this may vary as may the dose through the cycle), standard ovitrelle trigger and use of cylogest alone to pregnancy test day.\n\nSupplementary medication may occasional be required that is not included. We recommend purchasing medication from our pharmacy that is competitively priced either in person or via our courier service for ease and peace of mind but there is no obligation to do so.',
        AdditionalDrugNotes: null,
        Label: 'Starting dose',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      _225: {
        Value: '225',
        Order: '118',
        Cost: null,
        AdditionalDrugCost: '0',
        Notes:
          'Costs are based on a typical 12 day duration of stimulation (but this may vary as may the dose through the cycle), standard ovitrelle trigger and use of cylogest alone to pregnancy test day.\n\nSupplementary medication may occasional be required that is not included. We recommend purchasing medication from our pharmacy that is competitively priced either in person or via our courier service for ease and peace of mind but there is no obligation to do so.',
        AdditionalDrugNotes: null,
        Label: 'Starting dose',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      _300: {
        Value: '300',
        Order: '119',
        Cost: null,
        AdditionalDrugCost: '0',
        Notes:
          'Costs are based on a typical 12 day duration of stimulation (but this may vary as may the dose through the cycle), standard ovitrelle trigger and use of cylogest alone to pregnancy test day.\n\nSupplementary medication may occasional be required that is not included. We recommend purchasing medication from our pharmacy that is competitively priced either in person or via our courier service for ease and peace of mind but there is no obligation to do so.',
        AdditionalDrugNotes: null,
        Label: 'Starting dose',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      _375: {
        Value: '375',
        Order: '120',
        Cost: null,
        AdditionalDrugCost: '0',
        Notes:
          'Costs are based on a typical 12 day duration of stimulation (but this may vary as may the dose through the cycle), standard ovitrelle trigger and use of cylogest alone to pregnancy test day.\n\nSupplementary medication may occasional be required that is not included. We recommend purchasing medication from our pharmacy that is competitively priced either in person or via our courier service for ease and peace of mind but there is no obligation to do so.',
        AdditionalDrugNotes: null,
        Label: 'Starting dose',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      _450: {
        Value: '450',
        Order: '121',
        Cost: null,
        AdditionalDrugCost: '0',
        Notes:
          'Costs are based on a typical 12 day duration of stimulation (but this may vary as may the dose through the cycle), standard ovitrelle trigger and use of cylogest alone to pregnancy test day.\n\nSupplementary medication may occasional be required that is not included. We recommend purchasing medication from our pharmacy that is competitively priced either in person or via our courier service for ease and peace of mind but there is no obligation to do so.',
        AdditionalDrugNotes: null,
        Label: 'Starting dose',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
    },
    BlastocystCulture: {
      Yes: {
        Value: 'Yes',
        Order: '122',
        Cost: '999',
        AdditionalDrugCost: '0',
        Notes:
          'This includes Embryoscope used in all cycle and embryo glue where applicable. Blastocyst Culture to Day 5 and the use of AI to enhance embryo choice will be routinely recommended if there are a sufficient number of embryos on Day 3 as further culture will enhance embryo selection for transfer. There will be a 500 refund of the advanced embryology fee if embryos are not cultured beyond Day 3. This will not apply if embryos are cultured beyond Day 3 but no blastocysts are available for transfer or freeze.',
        AdditionalDrugNotes: null,
        Label: 'Blastocyst culture',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      No: {
        Value: 'No',
        Order: '123',
        Cost: '0',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Blastocyst culture',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
    },
    Adjuvants: {
      PGT_A_PGT_SR: {
        Value: 'PGT-A / PGT- SR',
        Order: '124',
        Cost: '1500',
        AdditionalDrugCost: '0',
        Notes:
          'This is costed for 2 embryos available for biopsy at £500/embryo along with the £500 PGT-A set-up fee.\nThis final cost will therefore depend on the number of embryos for testing.',
        AdditionalDrugNotes: null,
        Label: 'Adjuvants',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      EndometrialScratch: {
        Value: 'Endometrial Scratch',
        Order: '125',
        Cost: '350',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Adjuvants',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      Zymot: {
        Value: 'Zymot',
        Order: '126',
        Cost: '300',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Adjuvants',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      CalciumIonophore: {
        Value: 'Calcium Ionophore',
        Order: '127',
        Cost: '200',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Adjuvants',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      IntralipidInfusion: {
        Value: 'Intralipid Infusion',
        Order: '128',
        Cost: '43.26',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Adjuvants',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      IVIGInfusion: {
        Value: 'IVIG Infusion',
        Order: '129',
        Cost: '1270',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Adjuvants',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      AdditionalThawFreeze: {
        Value: 'Additional In-cycle Lab thaw/freeze',
        Order: '130',
        Cost: '550',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Adjuvants',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
    },
    CyclePrice: {
      MenopurLong_150: {
        Value: 'Menopur Long Protocol 150iu',
        Order: '131',
        Cost: '694.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      MenopurLong_225: {
        Value: 'Menopur Long Protocol 225iu',
        Order: '132',
        Cost: '834.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      MenopurLong_300: {
        Value: 'Menopur Long Protocol 300iu',
        Order: '133',
        Cost: '1122.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      MenopurLong_375: {
        Value: 'Menopur Long Protocol 375iu',
        Order: '134',
        Cost: '1270.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      MenopurLong_450: {
        Value: 'Menopur Long Protocol 450iu',
        Order: '135',
        Cost: '1558.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      MenopurAntagonist_150: {
        Value: 'Menopur Antagonist Protocol 150iu',
        Order: '136',
        Cost: '790.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      MenopurAntagonist_225: {
        Value: 'Menopur Antagonist Protocol 225iu',
        Order: '137',
        Cost: '930.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      MenopurAntagonist_300: {
        Value: 'Menopur Antagonist Protocol 300iu',
        Order: '138',
        Cost: '1218.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      MenopurAntagonist_375: {
        Value: 'Menopur Antagonist Protocol 375iu',
        Order: '139',
        Cost: '1366.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      MenopurAntagonist_450: {
        Value: 'Menopur Antagonist Protocol 450iu',
        Order: '140',
        Cost: '1654.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      GonalFLong_150: {
        Value: 'Gonal F Long Protocol 150iu',
        Order: '141',
        Cost: '890.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      GonalFLong_225: {
        Value: 'Gonal F Long Protocol 225iu',
        Order: '142',
        Cost: '1206.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      GonalFLong_300: {
        Value: 'Gonal F Long Protocol 300iu',
        Order: '143',
        Cost: '1522.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      GonalFLong_375: {
        Value: 'Gonal F Long Protocol 375iu',
        Order: '144',
        Cost: '1838.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      GonalFLong_450: {
        Value: 'Gonal F Long Protocol 450iu',
        Order: '145',
        Cost: '2154.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      GonalFAntagonist_150: {
        Value: 'Gonal F Antagonist Protocol 150iu',
        Order: '146',
        Cost: '986.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      GonalFAntagonist_225: {
        Value: 'Gonal F Antagonist Protocol 225iu',
        Order: '147',
        Cost: '1302.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      GonalFAntagonist_300: {
        Value: 'Gonal F Antagonist Protocol 300iu',
        Order: '148',
        Cost: '1618.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      GonalFAntagonist_375: {
        Value: 'Gonal F Antagonist Protocol 375iu',
        Order: '149',
        Cost: '1934.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      GonalFAntagonist_450: {
        Value: 'Gonal F Antagonist Protocol 450iu',
        Order: '150',
        Cost: '2250.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      MeriofertLong_150: {
        Value: 'Meriofert Long Protocol 150iu',
        Order: '151',
        Cost: '930.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      MeriofertLong_225: {
        Value: 'Meriofert Long Protocol 225iu',
        Order: '152',
        Cost: '1266.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      MeriofertLong_300: {
        Value: 'Meriofert Long Protocol 300iu',
        Order: '153',
        Cost: '1602.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      MeriofertLong_375: {
        Value: 'Meriofert Long Protocol 375iu',
        Order: '154',
        Cost: '1938.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      MeriofertLong_450: {
        Value: 'Meriofert Long Protocol 450iu',
        Order: '155',
        Cost: '2274.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      MeriofertAntagonist_150: {
        Value: 'Meriofert Antagonist Protocol 150iu',
        Order: '156',
        Cost: '1026.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      MeriofertAntagonist_225: {
        Value: 'Meriofert Antagonist Protocol 225iu',
        Order: '157',
        Cost: '1362.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      MeriofertAntagonist_300: {
        Value: 'Meriofert Antagonist Protocol 300iu',
        Order: '158',
        Cost: '1698.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      MeriofertAntagonist_375: {
        Value: 'Meriofert Antagonist Protocol 375iu',
        Order: '159',
        Cost: '2034.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      MeriofertAntagonist_450: {
        Value: 'Meriofert Antagonist Protocol 450iu',
        Order: '160',
        Cost: '2370.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      FostimonLong_150: {
        Value: 'Fostimon Long Protocol 150iu',
        Order: '161',
        Cost: '930.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      FostimonLong_225: {
        Value: 'Fostimon Long Protocol 225iu',
        Order: '162',
        Cost: '1266.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      FostimonLong_300: {
        Value: 'Fostimon Long Protocol 300iu',
        Order: '163',
        Cost: '1602.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      FostimonLong_375: {
        Value: 'Fostimon Long Protocol 375iu',
        Order: '164',
        Cost: '1938.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      FostimonLong_450: {
        Value: 'Fostimon Long Protocol 450iu',
        Order: '165',
        Cost: '2274.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      FostimonAntagonist_150: {
        Value: 'Fostimon Antagonist Protocol 150iu',
        Order: '166',
        Cost: '1026.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      FostimonAntagonist_225: {
        Value: 'Fostimon Antagonist Protocol 225iu',
        Order: '167',
        Cost: '1362.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      FostimonAntagonist_300: {
        Value: 'Fostimon Antagonist Protocol 300iu',
        Order: '168',
        Cost: '1698.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      FostimonAntagonist_375: {
        Value: 'Fostimon Antagonist Protocol 375iu',
        Order: '169',
        Cost: '2034.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      FostimonAntagonist_450: {
        Value: 'Fostimon Antagonist Protocol 450iu',
        Order: '170',
        Cost: '2370.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PergoverisLong_150: {
        Value: 'Pergoveris Long Protocol 150iu',
        Order: '171',
        Cost: '930.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PergoverisLong_225: {
        Value: 'Pergoveris Long Protocol 225iu',
        Order: '172',
        Cost: '1266.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PergoverisLong_300: {
        Value: 'Pergoveris Long Protocol 300iu',
        Order: '173',
        Cost: '1602.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PergoverisLong_375: {
        Value: 'Pergoveris Long Protocol 375iu',
        Order: '174',
        Cost: '1938.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PergoverisLong_450: {
        Value: 'Pergoveris Long Protocol 450iu',
        Order: '175',
        Cost: '2274.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PergoverisAntagonist_150: {
        Value: 'Pergoveris Antagonist Protocol 150iu',
        Order: '176',
        Cost: '1026.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PergoverisAntagonist_225: {
        Value: 'Pergoveris Antagonist Protocol 225iu',
        Order: '177',
        Cost: '1362.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PergoverisAntagonist_300: {
        Value: 'Pergoveris Antagonist Protocol 300iu',
        Order: '178',
        Cost: '1698.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PergoverisAntagonist_375: {
        Value: 'Pergoveris Antagonist Protocol 375iu',
        Order: '179',
        Cost: '2034.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
      PergoverisAntagonist_450: {
        Value: 'Pergoveris Antagonist Protocol 450iu',
        Order: '180',
        Cost: '2370.54',
        AdditionalDrugCost: '0',
        Notes: null,
        AdditionalDrugNotes: null,
        Label: 'Cycle drug',
        Cost1: null,
        Cost1Type: null,
        Cost2: null,
        Cost2Type: null,
      },
    },
  };

  useEffect(() => {
    // get data
    //axios.get(`${urlHost}/lookupApi/IVFCostCalculator/default/findbydictionaryasobject/Costs`)
    //    .then(response => {
    // console.log(response.data);

    // TODO replace with web call
    const response = new Object();
    response.data = costDataMock;

    setLoading(false);
    setCostData(response.data);
    let test = new Array(Object.keys(response.data.Adjuvants).length).fill(
      false
    );
    setCheckStatus(test);
    setIntroPDF(response.data?.Introduction?.Introduction?.Notes || '');
    setCalculatorHeading(
      response.data?.CalculatorHeading?.CalculatorHeading?.Notes || ''
    );
    setCycleTypeLabel(response.data?.Label?.CycleType?.Label || '');
    setBlastocystCultureLabel(
      response.data?.Label?.BlastocystCulture?.Label || ''
    );
    setStartingDoseLabel(response.data?.Label?.StartingDose?.Label || '');
    setProtocolTypeLabel(response.data?.Label?.ProtocolType?.Label || '');
    setStimulationDrugLabel(response.data?.Label?.StimulationDrug?.Label || '');
    setAdjuvantsLabel(response.data?.Label?.Adjuvants?.Label || '');
    setDrugPriceLabel(response.data?.Label?.DrugPrice?.Label || '');
    setCalculateButtonLabel(response.data?.Label?.CalculateButton?.Label || '');
    /*})
            .catch(error => {
                setLoading(false);
                setErrorData(true);
                console.log(error);
            })*/
    // eslint-disable-next-line
  }, []);

  return (
    <IvfCalculatorContext.Provider
      value={{
        urlHost,
        costData,
        setCostData,
        loading,
        setLoading,
        cycleTypeVal,
        setCycleTypeVal,
        protocolType,
        setProtocolType,
        stimulationDrug,
        setStimulationDrug,
        startingDose,
        setStartingDose,
        blastocystCulture,
        setBlastocystCulture,
        adjuvants,
        setAdjuvants,
        isDisabled,
        setIsDisabled,
        isProtocolType,
        setIsProtocolType,
        totalCost,
        setTotalCost,
        error,
        setError,
        isCalculating,
        setIsCalculating,
        checkStatus,
        setCheckStatus,
        cycleTypeCost,
        setCycleTypeCost,
        protocolTypeCost,
        setProtocolTypeCost,
        blastocystCultureCost,
        setBlastocystCultureCost,
        adjuvantsCost,
        setAdjuvantsCost,
        protocolNotes,
        setProtocolNotes,
        startingDoseNotes,
        setStartingDoseNotes,
        cycleNotes,
        setCycleNotes,
        cycleTypeAdditionalDrugNotes,
        setCycleTypeAdditionalDrugNotes,
        blastocystCultureNotes,
        setBlastocystCultureNotes,
        adjuvantsNotes,
        setAdjuvantsNotes,
        selectedDrugNotes,
        setSelectedDrugNotes,
        cycleCost,
        setCycleCost,
        selectedDrugValue,
        setSelectedDrugValue,
        adjuvantsValuesPrint,
        setAdjuvantsValuesPrint,
        introPDF,
        calculatorHeading,
        cycleTypeLabel,
        blastocystCultureLabel,
        startingDoseLabel,
        protocolTypeLabel,
        stimulationDrugLabel,
        adjuvantsLabel,
        drugPriceLabel,
        calculateButtonLabel,
        errorData,
        isStartingDrug,
        setIsStartingDrug,
        isStimulationDrug,
        setIsStimulationDrug,
        isBlastocyst,
        setIsBlastocyst,
        isAdjuvants,
        setIsAdjuvants,
      }}
    >
      {children}
    </IvfCalculatorContext.Provider>
  );
};

export default IvfCalculatorContextProvider;
