---
ID: "db22694e-25aa-4673-b048-0d262468d07e"
Parent: "ac8a0e35-b8d8-4ff6-8830-62947cf37ede"
Template: "ac8a0e35-b8d8-4ff6-8830-62947cf37ede"
Path: /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/GP and Urgent care services/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e3e2e54c-efb0-4c81-84d7-3fed70e84466"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\carmen.popovici@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231128T110822Z
