---
ID: "c571a8f1-0f26-44b0-9811-3bb6936aabe1"
Parent: "d8a7f56f-93b2-44bd-ac27-706adc4a99e5"
Template: "d8a7f56f-93b2-44bd-ac27-706adc4a99e5"
Path: /sitecore/templates/Project/HCA/Page Content/Homepage Service Cards Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {51E84F2D-E702-4C16-8E1F-94BB0EE75ED2}
    {D8A7F56F-93B2-44BD-AC27-706ADC4A99E5}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ab0af936-a802-4cde-b186-85bac5647f91"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\carmen.popovici@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231115T200950Z
