---
ID: "6c21b78c-751d-4b67-bdc5-9034f7979c51"
Parent: "9cff0180-277d-4be2-a118-c19ca31f2af6"
Template: "9cff0180-277d-4be2-a118-c19ca31f2af6"
Path: /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Stats Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "140df52b-3330-42f5-9119-af58b78e3242"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240909T161647Z
