---
<<<<<<<< HEAD:src/items/z HCA Project Mainsite site/HCA Main/Settings/Navigation Settings.yml
ID: "3f179d44-e6d3-455f-be8b-75a00c9a012e"
Parent: "7ff74119-335e-4011-91a2-c313a2ae4a2d"
Template: "64501c77-9428-4d19-88d9-17dc7905e510"
Path: /sitecore/content/HCA/HCA Main/Settings/Navigation Settings
========
ID: "92738908-c079-4709-957f-47386173d761"
Parent: "6c54c425-d4ce-4fa1-b75e-cf5313fc54d4"
Template: "49c111d0-6867-4798-a724-1f103166e6e9"
Path: /sitecore/content/HCA/HCA Main/Presentation/Headless Variants/Locations Map
>>>>>>>> dev:src/items/z HCA Project Mainsite site/HCA Main/Presentation/Headless Variants/Locations Map.yml
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
<<<<<<<< HEAD:src/items/z HCA Project Mainsite site/HCA Main/Settings/Navigation Settings.yml
      Value: 20240207T235602Z
========
      Value: 20240202T082924Z
>>>>>>>> dev:src/items/z HCA Project Mainsite site/HCA Main/Presentation/Headless Variants/Locations Map.yml
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\carmen.popovici@eqtr.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\carmen.popovici@eqtr.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
<<<<<<<< HEAD:src/items/z HCA Project Mainsite site/HCA Main/Settings/Navigation Settings.yml
      Value: "78f44616-b7cb-47e2-8072-564da8931421"
========
      Value: "21978861-8887-4a43-80b2-2438d0b16f34"
>>>>>>>> dev:src/items/z HCA Project Mainsite site/HCA Main/Presentation/Headless Variants/Locations Map.yml
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\carmen.popovici@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
<<<<<<<< HEAD:src/items/z HCA Project Mainsite site/HCA Main/Settings/Navigation Settings.yml
      Value: 20240207T235602Z
========
      Value: 20240202T082924Z
>>>>>>>> dev:src/items/z HCA Project Mainsite site/HCA Main/Presentation/Headless Variants/Locations Map.yml
