---
ID: "b1a07209-64ee-4092-91dd-0845370ec404"
Parent: "0cd0890a-f16a-497f-a9bc-b9e614b0ad4e"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Project/HCA/The Birth Company/Bookings/TBC Service Extras/Configuration
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250312T174531Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "cdea3d3d-d6f0-4995-823a-7d41536daad4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250312T204600Z
