---
ID: "5a9a2fa2-3c28-482f-8426-f9db9a973497"
Parent: "94ce9a95-00bf-419a-b6b8-1af89e886ed5"
Template: "94ce9a95-00bf-419a-b6b8-1af89e886ed5"
Path: /sitecore/templates/Project/HCA/Foundation/_HCABasePageData/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240325T133845Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\carmen.popovici@eqtr.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\carmen.popovici@eqtr.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a8a2bbb0-1d61-4f99-a23c-342c5a45c916"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\carmen.popovici@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240325T133918Z
    - ID: "dd6c2904-20c1-4670-b538-d523f08e60f0"
      Hint: Title
      Value: $name
