---
ID: "59fb7ede-e12c-41c0-b65c-e7dc4454ce2a"
Parent: "9b38cf34-6e17-48b6-b487-81931a90aa8a"
Template: "9b38cf34-6e17-48b6-b487-81931a90aa8a"
Path: /sitecore/templates/Project/HCA/Pages/Condition Page/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250206T120132Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7c4dc4d8-fc5d-4a09-8b40-b2df7386f9e4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250206T120132Z
