---
ID: "46b95092-4705-402d-b84d-a7a116aa9941"
Parent: "00ac6c64-dea6-42e1-9504-e2970ccd9fb1"
Template: "00ac6c64-dea6-42e1-9504-e2970ccd9fb1"
Path: /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/FAQ Block/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5cebb767-3770-46e0-be27-238d22c1fa34"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\naoum.zilas@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240123T104404Z
