---
ID: "8254e441-9b60-44cc-9dfe-8547d1c31ab4"
Parent: "155c3b4b-a898-42d8-b569-535841107aad"
Template: "155c3b4b-a898-42d8-b569-535841107aad"
Path: /sitecore/templates/Project/HCA/Navigation/Rendering Parameters/Sub Navigation Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9f52a1f3-7cff-4458-9339-623a2179f5a2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241114T153322Z
