---
ID: "567fc383-fc58-4024-bfc1-9319f873ed8a"
Parent: "be4cce0d-9280-4084-b5eb-52e962a574ca"
Template: "be4cce0d-9280-4084-b5eb-52e962a574ca"
Path: /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Patient stories/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "33840da7-9d75-41c8-9a52-4981a5ef797d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\carmen.popovici@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231124T124653Z
