---
ID: "89dabc56-9fbe-4d21-86cf-a0579f912aad"
Parent: "b74dd507-e9cd-4d69-9a91-e659ad427796"
Template: "b74dd507-e9cd-4d69-9a91-e659ad427796"
Path: /sitecore/templates/Project/HCA/Page Content/Logo Block/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{53863E35-28A7-4D9C-A965-6E502E1645AF}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240126T121354Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\naoum.zilas@eqtr.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\naoum.zilas@eqtr.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "35ff70e0-60e6-4db7-bd0e-a4099907c4f1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\naoum.zilas@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240126T121427Z
