---
ID: "b5ea9fa0-00db-4a92-9b54-f7591ab39866"
Parent: "8fab66d7-d5f7-4634-bb05-7dcb60831384"
Template: "8fab66d7-d5f7-4634-bb05-7dcb60831384"
Path: /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Pricing Information/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a11ab9d6-2eaf-40e5-b42f-22bbcff6ef62"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\carmen.popovici@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240402T105702Z
