---
ID: "69f5af43-faa0-4459-a5dc-492270e62ab5"
Parent: "1cd04bcb-65eb-4bf5-a625-e81dcd31d37d"
Template: "1cd04bcb-65eb-4bf5-a625-e81dcd31d37d"
Path: /sitecore/templates/Project/HCA/Consultant finder/Steps/StepLiveBookingConfirmation Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {A7F670F8-482C-4D28-8FB5-BB582E3AFFFA}
    {1CD04BCB-65EB-4BF5-A625-E81DCD31D37D}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ad790f11-368c-48a4-bd99-50a56cb0df26"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\matthew.hopkins@hcahealthcare.co.uk
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240116T134612Z
