---
ID: "9ce7beac-2a47-4293-b60a-56e6d675e271"
Parent: "ef671733-1250-45f5-8027-70cac198d2ef"
Template: "ef671733-1250-45f5-8027-70cac198d2ef"
Path: /sitecore/templates/Project/HCA/Consultant finder/Frames/CMA Disclosures Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {2726613E-A48F-451C-9ACA-FAF79D60D57A}
    {6D5657B8-EC00-409B-9499-F71872F851B9}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ff5ed7ce-5ada-48ce-a3f6-bcd0257681e7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\matthew.hopkins@hcahealthcare.co.uk
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240404T143838Z
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ff5ed7ce-5ada-48ce-a3f6-bcd0257681e7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\matthew.hopkins@hcahealthcare.co.uk
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240404T143838Z
