---
ID: "292cd99c-4cca-45e4-b49e-0d36e8f221e5"
Parent: "3e64bdcb-0966-4a73-8fc4-ec040329c957"
Template: "3e64bdcb-0966-4a73-8fc4-ec040329c957"
Path: /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Content Cards Slider Params/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "00bf1af9-41eb-4e11-b49e-8da3753deb7f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\carmen.popovici@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231201T140958Z
