---
ID: "7a080fbc-80bb-4233-8f8e-dfa8ef4108d9"
Parent: "d4706420-3df1-4009-8c25-9c306d91bd1e"
Template: "d4706420-3df1-4009-8c25-9c306d91bd1e"
Path: /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Plain Header Params/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a5bbbff4-f9c4-402c-8faa-96fe04e58586"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\naoum.zilas@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240125T124738Z
