---
ID: "0611ac98-ae76-41d4-bd1f-4e75a356cb7e"
Parent: "a877ef40-a3aa-49cb-80d7-39f2eb20f14e"
Template: "a877ef40-a3aa-49cb-80d7-39f2eb20f14e"
Path: /sitecore/templates/Project/HCA/Navigation/Breadcrumbs Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {7E2315E0-8EB2-4108-8F6E-7B5ACE223B0E}
    {A877EF40-A3AA-49CB-80D7-39F2EB20F14E}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0c6dbbfe-36e3-4312-9e55-07c0272f7ecd"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\carmen.popovici@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240210T132223Z
