
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { PSG as PSGProjectPSG } from "./PSG.Project.model"

export namespace PSG.Project.PSG {

    /**
    * Represents the template /sitecore/templates/Project/PSG/Headless Site
    */
    export type HeadlessSite =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/PSG/Headless Site
    */
    export type HeadlessSiteJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/PSG/Headless Tenant
    */
    export type HeadlessTenant =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/PSG/Headless Tenant
    */
    export type HeadlessTenantJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/PSG/JSS Settings
    */
    export type JssSettings =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/PSG/JSS Settings
    */
    export type JssSettingsJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/PSG/Page
    */
    export type Page =  {
        fields?: { 
            /**
            * Represents the Content field (88e58c08-03ea-4047-b8f9-7808c681b666).
            */
            Content?: Field<string>;

            /**
            * Represents the Title field (97f17700-443c-4628-bb3a-aa2f86e406eb).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/PSG/Page
    */
    export type PageJson =  {
        
            /**
            * Represents the Content field (88e58c08-03ea-4047-b8f9-7808c681b666).
            */
            Content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (97f17700-443c-4628-bb3a-aa2f86e406eb).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/PSG/Page Design Folder
    */
    export type PageDesignFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/PSG/Page Design Folder
    */
    export type PageDesignFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/PSG/Page Designs
    */
    export type PageDesigns =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/PSG/Page Designs
    */
    export type PageDesignsJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/PSG/Partial Design Folder
    */
    export type PartialDesignFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/PSG/Partial Design Folder
    */
    export type PartialDesignFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/PSG/Partial Designs
    */
    export type PartialDesigns =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/PSG/Partial Designs
    */
    export type PartialDesignsJson =  {
        

    }
}


