---
ID: "2ef5d21e-dc28-4952-b4aa-0398f3ad3d08"
Parent: "58c7ade7-c0c4-4fdf-b844-fbe221c162bd"
Template: "58c7ade7-c0c4-4fdf-b844-fbe221c162bd"
Path: /sitecore/templates/Project/HCA/Page Content/Intro Block/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{66038C46-E4E0-49BE-8D37-5D8EA90EBD7B}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231201T112053Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f5d5d8dc-3fe4-4d41-b2b9-9fcb5e462007"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\carmen.popovici@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231201T112105Z
