---
ID: "c098ab43-5383-4688-8757-5e4dd4f2096e"
Parent: "1542de84-cdf3-475e-8953-54d6cdc15ece"
Template: "1542de84-cdf3-475e-8953-54d6cdc15ece"
Path: /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Blog Text/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "cdeb71cf-1162-4c69-a7db-de309e4d5cdd"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260312T135055Z
