---
ID: "6ff174ad-3224-4f85-bdfc-9397679fe19c"
Parent: "1bd2226f-aa23-4eb4-9f59-b643131bb9d4"
Template: "1bd2226f-aa23-4eb4-9f59-b643131bb9d4"
Path: /sitecore/templates/Project/HCA/The Birth Company/Pregnancy Calculator/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250405T142406Z
    - ID: "46801b7e-49d3-44fe-9a4c-1855f9ee39ab"
      Hint: LastMenstrualPeriodFieldLabel
      Value: "When did your last menstrual period start?"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ad0e685a-6275-40fa-a839-a5e01e1a6d5d"
    - ID: "a9621526-b4bf-49d6-a747-6da87d523723"
      Hint: CTAText
      Value: Calculate
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "d6435d03-6a4a-48f8-9b2c-fb059057d1fb"
      Hint: Title
      Value: Pregnancy calculator
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250405T142435Z
