---
ID: "981edcc6-a972-4680-badd-4961cc31c7e2"
Parent: "d17f4c2d-4ae5-4c83-9db5-498589e205ae"
Template: "d17f4c2d-4ae5-4c83-9db5-498589e205ae"
Path: /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Contact Details Box Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250404T121401Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "63d8b704-9bd8-4d1e-b26d-bd7295ea4824"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250404T121401Z
