---
ID: "4e3ef7f7-87dc-405d-a51a-430feb9d9ff4"
Parent: "a5221ed0-6c71-4122-9bea-5ca059579383"
Template: "a5221ed0-6c71-4122-9bea-5ca059579383"
Path: /sitecore/templates/Project/HCA/Foundation/Logos/Logos Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{53863E35-28A7-4D9C-A965-6E502E1645AF}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240126T105555Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\naoum.zilas@eqtr.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\naoum.zilas@eqtr.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e56c5c4c-58e1-4180-b27f-f46c08fd3022"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\naoum.zilas@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240126T105608Z
