// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultServerImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, Fragment, jsxs } from 'react/jsx-runtime';
import { AppPlaceholder, RichText, Text, Link, Placeholder, Image } from '@sitecore-content-sdk/nextjs';
import componentMap from '.sitecore/component-map';
import React from 'react';
import Text_5660c949ca9a46e01d32019413f83db4dfe34e86 from '@component-library/foundation/Text/Text';
import { Default } from 'src/components/Page Content/Doctify/DoctifyGraphQl';
import { Default as Default_f7151e71b65df6ee8deb1c7c9323aad7148ff39e } from 'src/components/Page Content/CQCRating/CQCRatingGraphQl';
import SitecoreSvg from 'src/jss-abstractions/SitecoreSvg/SitecoreSvg';
import NextJssImage from 'src/jss-abstractions/NextJssImage/NextJssImage';
import dynamic from 'next/dynamic';
import RichText_581248f070c5ac493ea66e8ab7c6ff49a7d12c41 from '@component-library/core-components/RichText/RichText';
import PlaceHolderWrapper from 'src/jss-abstractions/PlaceholderWrapper/PlaceholderWrapper';
import { inPageNavGlobalStore } from 'src/context/inPageNavGlobalStorage';
import getHeadingTags from 'lib/getHeadingTags';
import Doctify from '@component-library/components/Doctify/Doctify';
import Button from '@component-library/core-components/Button/Button';
import TextButtonComponent from '@component-library/core-components/TextButton/TextButton';
import Icons from '@component-library/foundation/Icons/Icons';
import CQCBlock from '@component-library/components/CQCBlock/CQCBlock';
import { JumpToLink } from '@component-library/site-components/JumpToLinks/JumpToLinks';
import JumpToLinks from '@component-library/site-components/JumpToLinks/JumpToLinks';
import Themes from '@component-library/foundation/Themes/Themes';
import { linkReducer, columnMapper, SocialMediaCta } from 'src/components/Navigation/Footer/Footer.utilities';
import Footer from '@component-library/site-components/Footer/Footer';
import Breadcrumbs from '@component-library/site-components/Breadcrumbs/Breadcrumbs';
import Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 from 'next/link';
import Head from 'next/head';
import TextLink from '@component-library/core-components/TextLink/TextLink';
import FooterSmall from '@component-library/site-components/FooterSmall/FooterSmall';
import VacancyHeader from '@component-library/careers/VacancyHeader/VacancyHeader';
import { getDynamicTitleStyle } from '@component-library/site-components/HeaderPlain/HeaderPlain';
import { addThumbnailParameter } from 'lib/utility-functions/addThumbnailParameter';
import BlogContent from '@component-library/site-components/BlogContent/BlogContent';
import Container from '@component-library/foundation/Containers/Container';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'Fragment', value: Fragment },
      { name: 'jsxs', value: jsxs },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'AppPlaceholder', value: AppPlaceholder },
      { name: 'RichText', value: RichText },
      { name: 'Text', value: Text },
      { name: 'Link', value: Link },
      { name: 'Placeholder', value: Placeholder },
      { name: 'Image', value: Image },
    ]
  },
  {
    module: '.sitecore/component-map',
    exports: [
      { name: 'default', value: componentMap },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'default', value: React },
    ]
  },
  {
    module: '@component-library/foundation/Text/Text',
    exports: [
      { name: 'default', value: Text_5660c949ca9a46e01d32019413f83db4dfe34e86 },
    ]
  },
  {
    module: 'src/components/Page Content/Doctify/DoctifyGraphQl',
    exports: [
      { name: 'Default', value: Default },
    ]
  },
  {
    module: 'src/components/Page Content/CQCRating/CQCRatingGraphQl',
    exports: [
      { name: 'Default', value: Default_f7151e71b65df6ee8deb1c7c9323aad7148ff39e },
    ]
  },
  {
    module: 'src/jss-abstractions/SitecoreSvg/SitecoreSvg',
    exports: [
      { name: 'default', value: SitecoreSvg },
    ]
  },
  {
    module: 'src/jss-abstractions/NextJssImage/NextJssImage',
    exports: [
      { name: 'default', value: NextJssImage },
    ]
  },
  {
    module: 'next/dynamic',
    exports: [
      { name: 'default', value: dynamic },
    ]
  },
  {
    module: '@component-library/core-components/RichText/RichText',
    exports: [
      { name: 'default', value: RichText_581248f070c5ac493ea66e8ab7c6ff49a7d12c41 },
    ]
  },
  {
    module: 'src/jss-abstractions/PlaceholderWrapper/PlaceholderWrapper',
    exports: [
      { name: 'default', value: PlaceHolderWrapper },
    ]
  },
  {
    module: 'src/context/inPageNavGlobalStorage',
    exports: [
      { name: 'inPageNavGlobalStore', value: inPageNavGlobalStore },
    ]
  },
  {
    module: 'lib/getHeadingTags',
    exports: [
      { name: 'default', value: getHeadingTags },
    ]
  },
  {
    module: '@component-library/components/Doctify/Doctify',
    exports: [
      { name: 'default', value: Doctify },
    ]
  },
  {
    module: '@component-library/core-components/Button/Button',
    exports: [
      { name: 'default', value: Button },
    ]
  },
  {
    module: '@component-library/core-components/TextButton/TextButton',
    exports: [
      { name: 'default', value: TextButtonComponent },
    ]
  },
  {
    module: '@component-library/foundation/Icons/Icons',
    exports: [
      { name: 'default', value: Icons },
    ]
  },
  {
    module: '@component-library/components/CQCBlock/CQCBlock',
    exports: [
      { name: 'default', value: CQCBlock },
    ]
  },
  {
    module: '@component-library/site-components/JumpToLinks/JumpToLinks',
    exports: [
      { name: 'JumpToLink', value: JumpToLink },
      { name: 'default', value: JumpToLinks },
    ]
  },
  {
    module: '@component-library/foundation/Themes/Themes',
    exports: [
      { name: 'default', value: Themes },
    ]
  },
  {
    module: 'src/components/Navigation/Footer/Footer.utilities',
    exports: [
      { name: 'linkReducer', value: linkReducer },
      { name: 'columnMapper', value: columnMapper },
      { name: 'SocialMediaCta', value: SocialMediaCta },
    ]
  },
  {
    module: '@component-library/site-components/Footer/Footer',
    exports: [
      { name: 'default', value: Footer },
    ]
  },
  {
    module: '@component-library/site-components/Breadcrumbs/Breadcrumbs',
    exports: [
      { name: 'default', value: Breadcrumbs },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: '@component-library/core-components/TextLink/TextLink',
    exports: [
      { name: 'default', value: TextLink },
    ]
  },
  {
    module: '@component-library/site-components/FooterSmall/FooterSmall',
    exports: [
      { name: 'default', value: FooterSmall },
    ]
  },
  {
    module: '@component-library/careers/VacancyHeader/VacancyHeader',
    exports: [
      { name: 'default', value: VacancyHeader },
    ]
  },
  {
    module: '@component-library/site-components/HeaderPlain/HeaderPlain',
    exports: [
      { name: 'getDynamicTitleStyle', value: getDynamicTitleStyle },
    ]
  },
  {
    module: 'lib/utility-functions/addThumbnailParameter',
    exports: [
      { name: 'addThumbnailParameter', value: addThumbnailParameter },
    ]
  },
  {
    module: '@component-library/site-components/BlogContent/BlogContent',
    exports: [
      { name: 'default', value: BlogContent },
    ]
  },
  {
    module: '@component-library/foundation/Containers/Container',
    exports: [
      { name: 'default', value: Container },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultServerImportEntries, importMap);
