'use client';
  // This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, Fragment, jsxs } from 'react/jsx-runtime';
import { useRef, useMemo, createElement, useCallback, useEffect, useState } from 'react';
import React from 'react';
import { Text, RichText, Link as Link_8a80e63291fea86e0744df19113dc44bec187216, useComponentProps, debug, Image as Image_8a80e63291fea86e0744df19113dc44bec187216, CdpHelper, useSitecore } from '@sitecore-content-sdk/nextjs';
import Button from '@component-library/core-components/Button/Button';
import ModalAppointment from '@component-library/components/ModalAppointment/ModalAppointment';
import Text_5660c949ca9a46e01d32019413f83db4dfe34e86 from '@component-library/foundation/Text/Text';
import StickyCTA from '@component-library/site-components/StickyCTA/StickyCTA';
import Link from 'next/link';
import { withKeywordIdIfNeeded } from 'lib/doctify-integration/withKeywordIdIfNeeded';
import { SITECORE_TEMPLATE_IDS } from 'lib/sitecore/templateIds';
import { firstDoctifyMappedSelfOrAncestor } from 'lib/doctify-integration/firstDoctifyMappedSelfOrAncestor';
import { firstSelfOrAncestorByTemplate } from 'lib/doctify-integration/firstSelfOrAncestorByTemplate';
import { isValidNextLinkHref, normalizeHref } from 'lib/utility-functions/nextLinkHref';
import ModalCallUs from '@component-library/components/ModalCallUs/ModalCallUs';
import { OpeningHours } from 'src/jss-abstractions/OpeningHoursTextFormatting/OpeningHours';
import BlogContent from '@component-library/site-components/BlogContent/BlogContent';
import RichText_581248f070c5ac493ea66e8ab7c6ff49a7d12c41 from '@component-library/core-components/RichText/RichText';
import { inPageNavGlobalStore } from 'src/context/inPageNavGlobalStorage';
import { generateHtmlSafeId } from 'lib/utility-functions/generateHtmlSafeId';
import SearchBar from '@component-library/components/SearchBar/SearchBar';
import Checkboxes from '@component-library/core-components/Checkboxes/Checkboxes';
import Checkbox from '@component-library/core-components/Checkbox/Checkbox';
import Filters from '@component-library/site-components/Filters/Filters';
import Image from 'next/image';
import CardGrid from '@component-library/site-components/CardGrid/CardGrid';
import CardBlog from '@component-library/components/CardBlog/CardBlog';
import useSearchForm from '@component-library/hooks/useSearchForm/useSearchForm';
import SearchFormPagination from '@component-library/yext/SearchFormPagination/SearchFormPagination';
import getBaselineParams from 'lib/getBaselineParams';
import SearchContainer from '@component-library/site-components/SearchContainer/SearchContainer';
import Themes from '@component-library/foundation/Themes/Themes';
import SitecoreSvg from 'src/jss-abstractions/SitecoreSvg/SitecoreSvg';
import SearchFilterList from '@component-library/components/SearchFilterList/SearchFilterList';
import { getDynamicTitleStyle } from '@component-library/site-components/HeaderPlain/HeaderPlain';
import HeaderPlain from '@component-library/site-components/HeaderPlain/HeaderPlain';
import Tags from '@component-library/core-components/Tags/Tags';
import formatDate from 'src/jss-abstractions/JssDate/formatDate';
import unpackFilterOption from 'lib/unpackFilterOption';
import ErrorMessage from '@component-library/site-components/ErrorMessage/ErrorMessage';
import { useTranslations } from 'next-intl';
import SearchDetail from '@component-library/hooks/useSearchForm/components/SearchDetail';
import ImageUrl from 'src/jss-abstractions/ImageUrl';
import getHeadingTags from 'lib/getHeadingTags';
import { upsertQuerystringParam } from 'lib/utility-functions/addThumbnailParameter';
import CarouselCards from '@component-library/site-components/CarouselCards/CarouselCards';
import JssDate from 'src/jss-abstractions/JssDate/JssDate';
import JssTextWithEntityName from 'src/jss-abstractions/JssTextWithEntityName/JssTextWithEntityName';
import getSubheadingTag from 'lib/subheading-tag-getter';
import NextJssImage from 'src/jss-abstractions/NextJssImage/NextJssImage';
import dynamic from 'next/dynamic';
import Accordions from '@component-library/components/Accordions/Accordions';
import { JumpToAnchor, JumpToTextLink } from '@component-library/site-components/JumpToLinks/JumpToLinks';
import JumpToLinks from '@component-library/site-components/JumpToLinks/JumpToLinks';
import Icons from '@component-library/foundation/Icons/Icons';
import { usePathname, useSearchParams, useRouter } from 'next/navigation';
import Navigation from '@component-library/site-components/Navigation/Navigation';
import TextLink from '@component-library/core-components/TextLink/TextLink';
import ModalSearch from '@component-library/yext/ModalSearch/ModalSearch';
import { SEARCH_SUGGESTIONS_MODAL_ID } from 'lib/constants';
import client from 'src/lib/sitecore-client';
import { pageView } from '@sitecore-content-sdk/events';
import config from 'sitecore.config';
import useSWR from 'swr';
import YextResultCardCareers from '@component-library/yext/YextResultCardCareers/YextResultCardCareers';
import CareerSearchResults from '@component-library/careers/CareersSearchResults/CareersSearchResults';
import CareersHomepageHero from '@component-library/careers/CareersHompageHero/CareersHompageHero';
import SelectField from '@component-library/core-components/SelectField/SelectField';
import CareersSearch from '@component-library/careers/CareersSearch/CareersSearch';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'Fragment', value: Fragment },
      { name: 'jsxs', value: jsxs },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useRef', value: useRef },
      { name: 'useMemo', value: useMemo },
      { name: 'createElement', value: createElement },
      { name: 'useCallback', value: useCallback },
      { name: 'useEffect', value: useEffect },
      { name: 'useState', value: useState },
      { name: 'default', value: React },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Text', value: Text },
      { name: 'RichText', value: RichText },
      { name: 'Link', value: Link_8a80e63291fea86e0744df19113dc44bec187216 },
      { name: 'useComponentProps', value: useComponentProps },
      { name: 'debug', value: debug },
      { name: 'Image', value: Image_8a80e63291fea86e0744df19113dc44bec187216 },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'useSitecore', value: useSitecore },
    ]
  },
  {
    module: '@component-library/core-components/Button/Button',
    exports: [
      { name: 'default', value: Button },
    ]
  },
  {
    module: '@component-library/components/ModalAppointment/ModalAppointment',
    exports: [
      { name: 'default', value: ModalAppointment },
    ]
  },
  {
    module: '@component-library/foundation/Text/Text',
    exports: [
      { name: 'default', value: Text_5660c949ca9a46e01d32019413f83db4dfe34e86 },
    ]
  },
  {
    module: '@component-library/site-components/StickyCTA/StickyCTA',
    exports: [
      { name: 'default', value: StickyCTA },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link },
    ]
  },
  {
    module: 'lib/doctify-integration/withKeywordIdIfNeeded',
    exports: [
      { name: 'withKeywordIdIfNeeded', value: withKeywordIdIfNeeded },
    ]
  },
  {
    module: 'lib/sitecore/templateIds',
    exports: [
      { name: 'SITECORE_TEMPLATE_IDS', value: SITECORE_TEMPLATE_IDS },
    ]
  },
  {
    module: 'lib/doctify-integration/firstDoctifyMappedSelfOrAncestor',
    exports: [
      { name: 'firstDoctifyMappedSelfOrAncestor', value: firstDoctifyMappedSelfOrAncestor },
    ]
  },
  {
    module: 'lib/doctify-integration/firstSelfOrAncestorByTemplate',
    exports: [
      { name: 'firstSelfOrAncestorByTemplate', value: firstSelfOrAncestorByTemplate },
    ]
  },
  {
    module: 'lib/utility-functions/nextLinkHref',
    exports: [
      { name: 'isValidNextLinkHref', value: isValidNextLinkHref },
      { name: 'normalizeHref', value: normalizeHref },
    ]
  },
  {
    module: '@component-library/components/ModalCallUs/ModalCallUs',
    exports: [
      { name: 'default', value: ModalCallUs },
    ]
  },
  {
    module: 'src/jss-abstractions/OpeningHoursTextFormatting/OpeningHours',
    exports: [
      { name: 'OpeningHours', value: OpeningHours },
    ]
  },
  {
    module: '@component-library/site-components/BlogContent/BlogContent',
    exports: [
      { name: 'default', value: BlogContent },
    ]
  },
  {
    module: '@component-library/core-components/RichText/RichText',
    exports: [
      { name: 'default', value: RichText_581248f070c5ac493ea66e8ab7c6ff49a7d12c41 },
    ]
  },
  {
    module: 'src/context/inPageNavGlobalStorage',
    exports: [
      { name: 'inPageNavGlobalStore', value: inPageNavGlobalStore },
    ]
  },
  {
    module: 'lib/utility-functions/generateHtmlSafeId',
    exports: [
      { name: 'generateHtmlSafeId', value: generateHtmlSafeId },
    ]
  },
  {
    module: '@component-library/components/SearchBar/SearchBar',
    exports: [
      { name: 'default', value: SearchBar },
    ]
  },
  {
    module: '@component-library/core-components/Checkboxes/Checkboxes',
    exports: [
      { name: 'default', value: Checkboxes },
    ]
  },
  {
    module: '@component-library/core-components/Checkbox/Checkbox',
    exports: [
      { name: 'default', value: Checkbox },
    ]
  },
  {
    module: '@component-library/site-components/Filters/Filters',
    exports: [
      { name: 'default', value: Filters },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  },
  {
    module: '@component-library/site-components/CardGrid/CardGrid',
    exports: [
      { name: 'default', value: CardGrid },
    ]
  },
  {
    module: '@component-library/components/CardBlog/CardBlog',
    exports: [
      { name: 'default', value: CardBlog },
    ]
  },
  {
    module: '@component-library/hooks/useSearchForm/useSearchForm',
    exports: [
      { name: 'default', value: useSearchForm },
    ]
  },
  {
    module: '@component-library/yext/SearchFormPagination/SearchFormPagination',
    exports: [
      { name: 'default', value: SearchFormPagination },
    ]
  },
  {
    module: 'lib/getBaselineParams',
    exports: [
      { name: 'default', value: getBaselineParams },
    ]
  },
  {
    module: '@component-library/site-components/SearchContainer/SearchContainer',
    exports: [
      { name: 'default', value: SearchContainer },
    ]
  },
  {
    module: '@component-library/foundation/Themes/Themes',
    exports: [
      { name: 'default', value: Themes },
    ]
  },
  {
    module: 'src/jss-abstractions/SitecoreSvg/SitecoreSvg',
    exports: [
      { name: 'default', value: SitecoreSvg },
    ]
  },
  {
    module: '@component-library/components/SearchFilterList/SearchFilterList',
    exports: [
      { name: 'default', value: SearchFilterList },
    ]
  },
  {
    module: '@component-library/site-components/HeaderPlain/HeaderPlain',
    exports: [
      { name: 'getDynamicTitleStyle', value: getDynamicTitleStyle },
      { name: 'default', value: HeaderPlain },
    ]
  },
  {
    module: '@component-library/core-components/Tags/Tags',
    exports: [
      { name: 'default', value: Tags },
    ]
  },
  {
    module: 'src/jss-abstractions/JssDate/formatDate',
    exports: [
      { name: 'default', value: formatDate },
    ]
  },
  {
    module: 'lib/unpackFilterOption',
    exports: [
      { name: 'default', value: unpackFilterOption },
    ]
  },
  {
    module: '@component-library/site-components/ErrorMessage/ErrorMessage',
    exports: [
      { name: 'default', value: ErrorMessage },
    ]
  },
  {
    module: 'next-intl',
    exports: [
      { name: 'useTranslations', value: useTranslations },
    ]
  },
  {
    module: '@component-library/hooks/useSearchForm/components/SearchDetail',
    exports: [
      { name: 'default', value: SearchDetail },
    ]
  },
  {
    module: 'src/jss-abstractions/ImageUrl',
    exports: [
      { name: 'default', value: ImageUrl },
    ]
  },
  {
    module: 'lib/getHeadingTags',
    exports: [
      { name: 'default', value: getHeadingTags },
    ]
  },
  {
    module: 'lib/utility-functions/addThumbnailParameter',
    exports: [
      { name: 'upsertQuerystringParam', value: upsertQuerystringParam },
    ]
  },
  {
    module: '@component-library/site-components/CarouselCards/CarouselCards',
    exports: [
      { name: 'default', value: CarouselCards },
    ]
  },
  {
    module: 'src/jss-abstractions/JssDate/JssDate',
    exports: [
      { name: 'default', value: JssDate },
    ]
  },
  {
    module: 'src/jss-abstractions/JssTextWithEntityName/JssTextWithEntityName',
    exports: [
      { name: 'default', value: JssTextWithEntityName },
    ]
  },
  {
    module: 'lib/subheading-tag-getter',
    exports: [
      { name: 'default', value: getSubheadingTag },
    ]
  },
  {
    module: 'src/jss-abstractions/NextJssImage/NextJssImage',
    exports: [
      { name: 'default', value: NextJssImage },
    ]
  },
  {
    module: 'next/dynamic',
    exports: [
      { name: 'default', value: dynamic },
    ]
  },
  {
    module: '@component-library/components/Accordions/Accordions',
    exports: [
      { name: 'default', value: Accordions },
    ]
  },
  {
    module: '@component-library/site-components/JumpToLinks/JumpToLinks',
    exports: [
      { name: 'JumpToAnchor', value: JumpToAnchor },
      { name: 'JumpToTextLink', value: JumpToTextLink },
      { name: 'default', value: JumpToLinks },
    ]
  },
  {
    module: '@component-library/foundation/Icons/Icons',
    exports: [
      { name: 'default', value: Icons },
    ]
  },
  {
    module: 'next/navigation',
    exports: [
      { name: 'usePathname', value: usePathname },
      { name: 'useSearchParams', value: useSearchParams },
      { name: 'useRouter', value: useRouter },
    ]
  },
  {
    module: '@component-library/site-components/Navigation/Navigation',
    exports: [
      { name: 'default', value: Navigation },
    ]
  },
  {
    module: '@component-library/core-components/TextLink/TextLink',
    exports: [
      { name: 'default', value: TextLink },
    ]
  },
  {
    module: '@component-library/yext/ModalSearch/ModalSearch',
    exports: [
      { name: 'default', value: ModalSearch },
    ]
  },
  {
    module: 'lib/constants',
    exports: [
      { name: 'SEARCH_SUGGESTIONS_MODAL_ID', value: SEARCH_SUGGESTIONS_MODAL_ID },
    ]
  },
  {
    module: 'src/lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: '@sitecore-content-sdk/events',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  },
  {
    module: 'swr',
    exports: [
      { name: 'default', value: useSWR },
    ]
  },
  {
    module: '@component-library/yext/YextResultCardCareers/YextResultCardCareers',
    exports: [
      { name: 'default', value: YextResultCardCareers },
    ]
  },
  {
    module: '@component-library/careers/CareersSearchResults/CareersSearchResults',
    exports: [
      { name: 'default', value: CareerSearchResults },
    ]
  },
  {
    module: '@component-library/careers/CareersHompageHero/CareersHompageHero',
    exports: [
      { name: 'default', value: CareersHomepageHero },
    ]
  },
  {
    module: '@component-library/core-components/SelectField/SelectField',
    exports: [
      { name: 'default', value: SelectField },
    ]
  },
  {
    module: '@component-library/careers/CareersSearch/CareersSearch',
    exports: [
      { name: 'default', value: CareersSearch },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
