---
ID: "a0dfc046-40c8-44b1-8338-3aeea7748db6"
Parent: "f3ce8386-0b63-44b5-a204-eae92c052aae"
Template: "f3ce8386-0b63-44b5-a204-eae92c052aae"
Path: /sitecore/templates/Project/HCA/Careers/Base/_careersJobTextSearchFilter/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250206T120137Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9346913f-a1dd-49f5-af6f-5740a36dac9a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250206T120137Z
