---
ID: "8736670b-7b6a-49c0-88e2-44c995336c9a"
Parent: "bbdee272-cfbe-49cd-aed0-fbbd11419314"
Template: "bbdee272-cfbe-49cd-aed0-fbbd11419314"
Path: /sitecore/templates/Project/HCA/Business/Opening Hours/DaysOfWeekFolder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{6F19B186-DFDE-4FA1-977C-F0A23E2C469A}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240123T152757Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\5dv29vxgiA
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\5dv29vxgiA
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1f56eb63-25cb-4fc9-aa47-20bbeb796222"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\5dv29vxgiA
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240123T152828Z
