---
ID: "0d47d79d-70c3-4ee0-b2f2-c21020e2875e"
Parent: "4dfe7daa-4281-410b-aa42-6b3f5bc3b4e0"
Template: "4dfe7daa-4281-410b-aa42-6b3f5bc3b4e0"
Path: /sitecore/templates/Project/PSG/Page Design Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {4DFE7DAA-4281-410B-AA42-6B3F5BC3B4E0}
    {1105B8F8-1E00-426B-BF1F-C840742D827B}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231009T103648Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "50cb4167-f42c-404a-97bf-cdf2559fd55a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231009T103653Z
