---
ID: "cda1faf1-ce46-416f-88bf-e0bb7c97addd"
Parent: "de728119-8e4d-44d2-9fdc-de48a2539fd4"
Template: "de728119-8e4d-44d2-9fdc-de48a2539fd4"
Path: /sitecore/templates/Project/HCA/Foundation/Share/_ShareBase/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250206T120131Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d566e3b5-a505-4ba8-9446-7d9d0b9a5bdb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250206T120131Z
