---
ID: "8827c1dc-f7c9-4e05-8815-a636f92d5ab2"
Parent: "ce1e735e-88aa-417a-bffe-9e80a1245e7b"
Template: "ce1e735e-88aa-417a-bffe-9e80a1245e7b"
Path: /sitecore/templates/Project/HCA/Foundation/Video Providers/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250206T120131Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "de9a37a3-6e36-41f6-a6be-6406df28f95b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250206T120131Z
