---
ID: "879f3b57-d239-40d3-9330-896c646ad1e6"
Parent: "211fcae2-55d3-49f5-b28c-f6ec8cdbccda"
Template: "211fcae2-55d3-49f5-b28c-f6ec8cdbccda"
Path: /sitecore/templates/Project/HCA/Page Content/Accordions/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{98FBB3DE-2BCA-438E-81E0-6BBF94FC13D9}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240124T095727Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\naoum.zilas@eqtr.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\naoum.zilas@eqtr.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e1fd6033-aa21-4fef-8e3a-36fed5646573"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241125T125725Z
