---
ID: "1b0b95e0-6248-4785-9dd2-fad1d5af8bf4"
Parent: "0e970b52-7e12-4abe-ab9c-bbd0d2dd9ee3"
Template: "0e970b52-7e12-4abe-ab9c-bbd0d2dd9ee3"
Path: /sitecore/templates/Project/HCA/Page Content/Authors/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1ccca1cb-4436-4355-9389-4bbcc6941d18"
      Hint: Title
      Value: Reviewed by
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240930T115220Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3c54b9c1-aab5-42eb-bf24-e83548384319"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240930T115229Z
