
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { PageContent as HCAProjectPageContent } from "./HCA.Project.model"
// @ts-ignore 
import { Foundation as HCAProjectFoundation } from "./HCA.Project.model"
// @ts-ignore 
import { Pages as HCAProjectPages } from "./HCA.Project.model"
// @ts-ignore 
import { HCA as HCAProjectHCA } from "./HCA.Project.model"

export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Amenities
    */
    export type Amenities =  {
        fields?: { 
            /**
            * Represents the Amenities List field (5455a723-12c3-4842-8008-268c45cf5ed9).
            */
            "Amenities List"?: Item[];

            /**
            * Represents the Image field (6198bd6f-14ad-4894-be7c-486fa8bcf2fc).
            */
            Image?: ImageField;

            /**
            * Represents the Text field (108d5af2-f154-40d8-9f38-52972a67a897).
            */
            Text?: Field<string>;

            /**
            * Represents the Title field (5bcb634d-fb9e-440c-8258-432b2475df21).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Amenities
    */
    export type AmenitiesJson =  {
        
            /**
            * Represents the Amenities List field (5455a723-12c3-4842-8008-268c45cf5ed9).
            */
            "Amenities List"?: {
                jsonValue: Item[]
            };

            /**
            * Represents the Image field (6198bd6f-14ad-4894-be7c-486fa8bcf2fc).
            */
            Image?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Text field (108d5af2-f154-40d8-9f38-52972a67a897).
            */
            Text?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (5bcb634d-fb9e-440c-8258-432b2475df21).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace PageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Amenities
    */
    export type Amenities = HCAProjectFoundation.HeadingParameters &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Amenities
    */
    export type AmenitiesJson = HCAProjectFoundation.HeadingParametersJson &  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Amenities Folder
    */
    export type AmenitiesFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Amenities Folder
    */
    export type AmenitiesFolderJson =  {
        

    }
}
export namespace Foundation.Amenities {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Amenities/Amenities Folder
    */
    export type AmenitiesFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Amenities/Amenities Folder
    */
    export type AmenitiesFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Amenities/Amenity
    */
    export type Amenity =  {
        fields?: { 
            /**
            * Represents the Icon field (65a9ef0d-857e-4201-a474-2f91662e3817).
            */
            Icon?: Item;

            /**
            * Represents the Title field (a17e6d73-e816-4f01-bb73-49e5596311be).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Amenities/Amenity
    */
    export type AmenityJson =  {
        
            /**
            * Represents the Icon field (65a9ef0d-857e-4201-a474-2f91662e3817).
            */
            Icon?: {
                jsonValue: Item
            };

            /**
            * Represents the Title field (a17e6d73-e816-4f01-bb73-49e5596311be).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace Pages {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Pages/Blog Page
    */
    export type BlogPage = HCAProjectFoundation.HcabasePage &  {
        fields?: { 
            /**
            * Represents the Date field (e1b9a21b-a32e-429b-bbe5-047b323fd263).
            */
            Date?: Field<string>;

            /**
            * Represents the Tags field (2fa63bb5-b5b6-4ce7-85ef-36b6b3352524).
            */
            Tags?: Item[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Pages/Blog Page
    */
    export type BlogPageJson = HCAProjectFoundation.HcabasePageJson &  {
        
            /**
            * Represents the Date field (e1b9a21b-a32e-429b-bbe5-047b323fd263).
            */
            Date?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Tags field (2fa63bb5-b5b6-4ce7-85ef-36b6b3352524).
            */
            Tags?: {
                jsonValue: Item[]
            };


    }
}
export namespace Foundation.Cqc {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/CQC/CQC
    */
    export type Cqc = HCAProjectFoundation.CqcbasePage &  {
        fields?: { 
            /**
            * Represents the Text field (fd25675b-a6f6-4fc9-be43-f7b1eed271cb).
            */
            Text?: Field<string>;

            /**
            * Represents the Title field (b5cfb002-6c07-4b59-953f-abb43486f0ce).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/CQC/CQC
    */
    export type CqcJson = HCAProjectFoundation.CqcbasePageJson &  {
        
            /**
            * Represents the Text field (fd25675b-a6f6-4fc9-be43-f7b1eed271cb).
            */
            Text?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (b5cfb002-6c07-4b59-953f-abb43486f0ce).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/CQC/CQC Folder
    */
    export type CqcFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/CQC/CQC Folder
    */
    export type CqcFolderJson =  {
        

    }
}
export namespace Foundation.Settings {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Settings/CQC Settings
    */
    export type CqcSettings =  {
        fields?: { 
            /**
            * Represents the Logo field (deaa091e-8c4e-4093-ad6a-f79f00b2521a).
            */
            Logo?: ImageField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Settings/CQC Settings
    */
    export type CqcSettingsJson =  {
        
            /**
            * Represents the Logo field (deaa091e-8c4e-4093-ad6a-f79f00b2521a).
            */
            Logo?: {
                jsonValue: ImageField
            };


    }
}
export namespace Foundation.Cqc {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/CQC/CQC Status
    */
    export type CqcStatus =  {
        fields?: { 
            /**
            * Represents the CQC Logo field (cac4f9dc-c36a-4c56-97db-ebce1e7e2f29).
            */
            "CQC Logo"?: Item;

            /**
            * Represents the Icon field (f7469f76-595c-49cc-b0cc-66a5e3d33383).
            */
            Icon?: Field<string>;

            /**
            * Represents the Title field (7edb9b23-9055-4551-a6d4-edca5a3f364d).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/CQC/CQC Status
    */
    export type CqcStatusJson =  {
        
            /**
            * Represents the CQC Logo field (cac4f9dc-c36a-4c56-97db-ebce1e7e2f29).
            */
            "CQC Logo"?: {
                jsonValue: Item
            };

            /**
            * Represents the Icon field (f7469f76-595c-49cc-b0cc-66a5e3d33383).
            */
            Icon?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (7edb9b23-9055-4551-a6d4-edca5a3f364d).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/CQC/CQC Statuses Folder
    */
    export type CqcStatusesFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/CQC/CQC Statuses Folder
    */
    export type CqcStatusesFolderJson =  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/CTA Button
    */
    export type CtaButton = HCAProjectFoundation.Ctabase &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/CTA Button
    */
    export type CtaButtonJson = HCAProjectFoundation.CtabaseJson &  {
        

    }
}
export namespace PageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/CTA Button
    */
    export type CtaButton =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/CTA Button
    */
    export type CtaButtonJson =  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/CTA Button Folder
    */
    export type CtaButtonFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/CTA Button Folder
    */
    export type CtaButtonFolderJson =  {
        

    }
}
export namespace Foundation.ContentCard {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Content Card/Content Card
    */
    export type ContentCard =  {
        fields?: { 
            /**
            * Represents the Image field (d8fecc64-a0b7-4e73-b436-929a62a044ee).
            */
            Image?: ImageField;

            /**
            * Represents the Text field (ce8136f4-2e0b-4236-af51-e522ee8ab699).
            */
            Text?: Field<string>;

            /**
            * Represents the Title field (57f21df8-fa55-4267-8bb7-743b504d1ddd).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Content Card/Content Card
    */
    export type ContentCardJson =  {
        
            /**
            * Represents the Image field (d8fecc64-a0b7-4e73-b436-929a62a044ee).
            */
            Image?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Text field (ce8136f4-2e0b-4236-af51-e522ee8ab699).
            */
            Text?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (57f21df8-fa55-4267-8bb7-743b504d1ddd).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Content Card/Content Card Folder
    */
    export type ContentCardFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Content Card/Content Card Folder
    */
    export type ContentCardFolderJson =  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Content Cards
    */
    export type ContentCards =  {
        fields?: { 
            /**
            * Represents the CTA Card Text field (cddfe7c4-c61f-48a4-8719-85e660642a13).
            */
            "CTA Card Text"?: Field<string>;

            /**
            * Represents the Pages field (e6568c06-70ff-4b88-b5ed-44a0bd98df50).
            */
            Pages?: Item[];

            /**
            * Represents the Title field (7271b4dd-8299-46fc-b5a1-d2422b5e4fc3).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Content Cards
    */
    export type ContentCardsJson =  {
        
            /**
            * Represents the CTA Card Text field (cddfe7c4-c61f-48a4-8719-85e660642a13).
            */
            "CTA Card Text"?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Pages field (e6568c06-70ff-4b88-b5ed-44a0bd98df50).
            */
            Pages?: {
                jsonValue: Item[]
            };

            /**
            * Represents the Title field (7271b4dd-8299-46fc-b5a1-d2422b5e4fc3).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace PageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Content Cards
    */
    export type ContentCards = HCAProjectFoundation.HeadingParameters &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Content Cards
    */
    export type ContentCardsJson = HCAProjectFoundation.HeadingParametersJson &  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Content Cards Folder
    */
    export type ContentCardsFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Content Cards Folder
    */
    export type ContentCardsFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Content Cards Slider
    */
    export type ContentCardsSlider = HCAProjectFoundation.Ctabase &  {
        fields?: { 
            /**
            * Represents the CTA Card Text field (0120cb1f-140d-43eb-8ed4-aac38f98dcf0).
            */
            "CTA Card Text"?: Field<string>;

            /**
            * Represents the Heading field (2ffa16c6-9052-4ce3-9a81-95694b145328).
            */
            Heading?: Field<string>;

            /**
            * Represents the Pages field (8c120705-ad32-4f5e-a87e-84b01b1f2d83).
            */
            Pages?: Item[];

            /**
            * Represents the Title field (17be2717-992a-4d65-918b-07bb26210837).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Content Cards Slider
    */
    export type ContentCardsSliderJson = HCAProjectFoundation.CtabaseJson &  {
        
            /**
            * Represents the CTA Card Text field (0120cb1f-140d-43eb-8ed4-aac38f98dcf0).
            */
            "CTA Card Text"?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Heading field (2ffa16c6-9052-4ce3-9a81-95694b145328).
            */
            Heading?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Pages field (8c120705-ad32-4f5e-a87e-84b01b1f2d83).
            */
            Pages?: {
                jsonValue: Item[]
            };

            /**
            * Represents the Title field (17be2717-992a-4d65-918b-07bb26210837).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace PageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Content Cards Slider
    */
    export type ContentCardsSlider = HCAProjectFoundation.HeadingParameters &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Content Cards Slider
    */
    export type ContentCardsSliderJson = HCAProjectFoundation.HeadingParametersJson &  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Content Cards Slider Folder
    */
    export type ContentCardsSliderFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Content Cards Slider Folder
    */
    export type ContentCardsSliderFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Content carousel
    */
    export type ContentCarousel =  {
        fields?: { 
            /**
            * Represents the Cards field (13620367-04c6-4085-98fe-4980726cc3bd).
            */
            Cards?: Item[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Content carousel
    */
    export type ContentCarouselJson =  {
        
            /**
            * Represents the Cards field (13620367-04c6-4085-98fe-4980726cc3bd).
            */
            Cards?: {
                jsonValue: Item[]
            };


    }
}
export namespace PageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Content carousel
    */
    export type ContentCarousel = HCAProjectFoundation.HeadingParameters & 
HCAProjectFoundation.ThemesParameters &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Content carousel
    */
    export type ContentCarouselJson = HCAProjectFoundation.HeadingParametersJson & 
HCAProjectFoundation.ThemesParametersJson &  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Content carousel Folder
    */
    export type ContentCarouselFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Content carousel Folder
    */
    export type ContentCarouselFolderJson =  {
        

    }
}
export namespace Foundation.Settings {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Settings/Custom Settings Folder
    */
    export type CustomSettingsFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Settings/Custom Settings Folder
    */
    export type CustomSettingsFolderJson =  {
        

    }
}
export namespace Foundation.Doctify {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Doctify/Doctify Filter
    */
    export type DoctifyFilter =  {
        fields?: { 
            /**
            * Represents the Filter field (51584e8c-360b-47ea-96e0-bd5d45dec2af).
            */
            Filter?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Doctify/Doctify Filter
    */
    export type DoctifyFilterJson =  {
        
            /**
            * Represents the Filter field (51584e8c-360b-47ea-96e0-bd5d45dec2af).
            */
            Filter?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Doctify/Doctify Filters
    */
    export type DoctifyFilters =  {
        fields?: { 
            /**
            * Represents the Custom Filters field (ab11cab9-17e6-42ac-98ca-aec3d7127a85).
            */
            "Custom Filters"?: Item[];

            /**
            * Represents the Practice field (d4e8f601-4189-4c53-a450-1b938d34f437).
            */
            Practice?: Item[];

            /**
            * Represents the Service field (e1dd6602-4ddc-4428-a336-986c1a3e5583).
            */
            Service?: Item[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Doctify/Doctify Filters
    */
    export type DoctifyFiltersJson =  {
        
            /**
            * Represents the Custom Filters field (ab11cab9-17e6-42ac-98ca-aec3d7127a85).
            */
            "Custom Filters"?: {
                jsonValue: Item[]
            };

            /**
            * Represents the Practice field (d4e8f601-4189-4c53-a450-1b938d34f437).
            */
            Practice?: {
                jsonValue: Item[]
            };

            /**
            * Represents the Service field (e1dd6602-4ddc-4428-a336-986c1a3e5583).
            */
            Service?: {
                jsonValue: Item[]
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Doctify/Doctify Filters Folder
    */
    export type DoctifyFiltersFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Doctify/Doctify Filters Folder
    */
    export type DoctifyFiltersFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Doctify/Doctify Reviews
    */
    export type DoctifyReviews =  {
        fields?: { 
            /**
            * Represents the Reviews field (ef0cf15c-3c69-4958-9cc1-e71ad136219d).
            */
            Reviews?: Field<string>;

            /**
            * Represents the Stars field (8768d68c-852a-48ad-98d6-f5b0ddac4fbd).
            */
            Stars?: Field<number>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Doctify/Doctify Reviews
    */
    export type DoctifyReviewsJson =  {
        
            /**
            * Represents the Reviews field (ef0cf15c-3c69-4958-9cc1-e71ad136219d).
            */
            Reviews?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Stars field (8768d68c-852a-48ad-98d6-f5b0ddac4fbd).
            */
            Stars?: {
                jsonValue: Field<number>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Doctify/Doctify Reviews Folder
    */
    export type DoctifyReviewsFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Doctify/Doctify Reviews Folder
    */
    export type DoctifyReviewsFolderJson =  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Doctor cards
    */
    export type DoctorCards = HCAProjectFoundation.Doctify.DoctifyFilters & 
HCAProjectFoundation.Ctabase &  {
        fields?: { 
            /**
            * Represents the CTA Card field (5a674cd7-c9eb-4be4-8577-5c3d6d72c70c).
            */
            "CTA Card"?: LinkField;

            /**
            * Represents the Number of Cards field (f75ab386-350c-44ca-97a1-3b63a8a61cdc).
            */
            "Number of Cards"?: Field<number>;

            /**
            * Represents the Title field (fd86c684-2a05-4705-8d10-4eb1bc9156f5).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Doctor cards
    */
    export type DoctorCardsJson = HCAProjectFoundation.Doctify.DoctifyFiltersJson & 
HCAProjectFoundation.CtabaseJson &  {
        
            /**
            * Represents the CTA Card field (5a674cd7-c9eb-4be4-8577-5c3d6d72c70c).
            */
            "CTA Card"?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Number of Cards field (f75ab386-350c-44ca-97a1-3b63a8a61cdc).
            */
            "Number of Cards"?: {
                jsonValue: Field<number>
            };

            /**
            * Represents the Title field (fd86c684-2a05-4705-8d10-4eb1bc9156f5).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace PageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Doctor cards
    */
    export type DoctorCards = HCAProjectFoundation.HeadingParameters &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Doctor cards
    */
    export type DoctorCardsJson = HCAProjectFoundation.HeadingParametersJson &  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Doctor cards Folder
    */
    export type DoctorCardsFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Doctor cards Folder
    */
    export type DoctorCardsFolderJson =  {
        

    }
}
export namespace Foundation {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/HCAIcon
    */
    export type Hcaicon =  {
        fields?: { 
            /**
            * Represents the SVG Markup field (f42617c7-46b7-46f3-a075-69ebf514838e).
            */
            SvgMarkup?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/HCAIcon
    */
    export type HcaiconJson =  {
        
            /**
            * Represents the SVG Markup field (f42617c7-46b7-46f3-a075-69ebf514838e).
            */
            SvgMarkup?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/HeadingParameters
    */
    export type HeadingParameters =  {
        fields?: { 
            /**
            * Represents the HeadingSize field (b791330d-3cf2-4c11-a07f-5a29d392c972).
            */
            HeadingSize?: Field<string>;

            /**
            * Represents the HeadingTag field (be0ce91d-874a-4f9c-8418-6c173f5593af).
            */
            HeadingTag?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/HeadingParameters
    */
    export type HeadingParametersJson =  {
        
            /**
            * Represents the HeadingSize field (b791330d-3cf2-4c11-a07f-5a29d392c972).
            */
            HeadingSize?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the HeadingTag field (be0ce91d-874a-4f9c-8418-6c173f5593af).
            */
            HeadingTag?: {
                jsonValue: Field<string>
            };


    }
}
export namespace HCA.Project.HCA {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Headless Site
    */
    export type HeadlessSite =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Headless Site
    */
    export type HeadlessSiteJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Headless Tenant
    */
    export type HeadlessTenant =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Headless Tenant
    */
    export type HeadlessTenantJson =  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Homepage cards - Blog Cards
    */
    export type HomepageCardsBlogCards = HCAProjectFoundation.Ctabase &  {
        fields?: { 
            /**
            * Represents the Cards field (c58c6d3c-8e54-479b-bd03-8c0b579549d2).
            */
            Cards?: Item[];

            /**
            * Represents the Title field (88bcb0ec-8511-4635-98cd-f55abd041468).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Homepage cards - Blog Cards
    */
    export type HomepageCardsBlogCardsJson = HCAProjectFoundation.CtabaseJson &  {
        
            /**
            * Represents the Cards field (c58c6d3c-8e54-479b-bd03-8c0b579549d2).
            */
            Cards?: {
                jsonValue: Item[]
            };

            /**
            * Represents the Title field (88bcb0ec-8511-4635-98cd-f55abd041468).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace PageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Homepage cards - Blog Pages
    */
    export type HomepageCardsBlogPages = HCAProjectFoundation.HeadingParameters &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Homepage cards - Blog Pages
    */
    export type HomepageCardsBlogPagesJson = HCAProjectFoundation.HeadingParametersJson &  {
        

    }
}
export namespace Foundation {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Icons Folder
    */
    export type IconsFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Icons Folder
    */
    export type IconsFolderJson =  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Intro Block
    */
    export type IntroBlock = HCAProjectFoundation.Ctabase &  {
        fields?: { 
            /**
            * Represents the Counters field (d0db9d3f-ad94-4795-ae43-5c3ce95ea702).
            */
            Counters?: Item[];

            /**
            * Represents the CQC Status field (a238486c-a225-48be-be0a-864e6fe4e0e0).
            */
            "CQC Status"?: Item;

            /**
            * Represents the Doctify Reviews field (c1ad7d36-37ef-40e0-a5f8-749f50c0ae13).
            */
            "Doctify Reviews"?: Item;

            /**
            * Represents the Image field (235db187-da6f-4bb9-a6ad-a281cb8af961).
            */
            Image?: ImageField;

            /**
            * Represents the Text field (7b92fe8b-f992-41d1-bd78-93b8e82b81d1).
            */
            Text?: Field<string>;

            /**
            * Represents the Title field (b9bb0431-2236-460a-8136-154adf67e91c).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Intro Block
    */
    export type IntroBlockJson = HCAProjectFoundation.CtabaseJson &  {
        
            /**
            * Represents the Counters field (d0db9d3f-ad94-4795-ae43-5c3ce95ea702).
            */
            Counters?: {
                jsonValue: Item[]
            };

            /**
            * Represents the CQC Status field (a238486c-a225-48be-be0a-864e6fe4e0e0).
            */
            "CQC Status"?: {
                jsonValue: Item
            };

            /**
            * Represents the Doctify Reviews field (c1ad7d36-37ef-40e0-a5f8-749f50c0ae13).
            */
            "Doctify Reviews"?: {
                jsonValue: Item
            };

            /**
            * Represents the Image field (235db187-da6f-4bb9-a6ad-a281cb8af961).
            */
            Image?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Text field (7b92fe8b-f992-41d1-bd78-93b8e82b81d1).
            */
            Text?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (b9bb0431-2236-460a-8136-154adf67e91c).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace PageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Intro Block
    */
    export type IntroBlock = HCAProjectFoundation.HeadingParameters &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Intro Block
    */
    export type IntroBlockJson = HCAProjectFoundation.HeadingParametersJson &  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Intro Block Folder
    */
    export type IntroBlockFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Intro Block Folder
    */
    export type IntroBlockFolderJson =  {
        

    }
}
export namespace HCA.Project.HCA {

    /**
    * Represents the template /sitecore/templates/Project/HCA/JSS Settings
    */
    export type JssSettings =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/JSS Settings
    */
    export type JssSettingsJson =  {
        

    }
}
export namespace Pages {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Pages/Location Page
    */
    export type LocationPage = HCAProjectFoundation.HcabasePage & 
HCAProjectFoundation.Doctify.DoctifyPracticeMapping &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Pages/Location Page
    */
    export type LocationPageJson = HCAProjectFoundation.HcabasePageJson & 
HCAProjectFoundation.Doctify.DoctifyPracticeMappingJson &  {
        

    }
}
export namespace HCA.Project.HCA {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page
    */
    export type Page =  {
        fields?: { 
            /**
            * Represents the Content field (38b0e5ab-0239-472e-8605-a55987ae3f43).
            */
            Content?: Field<string>;

            /**
            * Represents the Title field (f253d55f-c5e7-4bbd-8423-45ee6c8a12ec).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page
    */
    export type PageJson =  {
        
            /**
            * Represents the Content field (38b0e5ab-0239-472e-8605-a55987ae3f43).
            */
            Content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (f253d55f-c5e7-4bbd-8423-45ee6c8a12ec).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Design Folder
    */
    export type PageDesignFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Design Folder
    */
    export type PageDesignFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Designs
    */
    export type PageDesigns =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Designs
    */
    export type PageDesignsJson =  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Page Proxy
    */
    export type PageProxy = HCAProjectFoundation.HcabasePageData &  {
        fields?: { 
            /**
            * Represents the Link field (1b699dd6-99de-4058-a91d-f3fd23b47e41).
            */
            Link?: LinkField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Page Proxy
    */
    export type PageProxyJson = HCAProjectFoundation.HcabasePageDataJson &  {
        
            /**
            * Represents the Link field (1b699dd6-99de-4058-a91d-f3fd23b47e41).
            */
            Link?: {
                jsonValue: LinkField
            };


    }
}
export namespace Foundation {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Page Proxy
    */
    export type PageProxy = HCAProjectFoundation.HcabasePageData &  {
        fields?: { 
            /**
            * Represents the Link field (3317a6f6-dbe7-4cbb-a826-605fef277ad5).
            */
            Link?: LinkField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Page Proxy
    */
    export type PageProxyJson = HCAProjectFoundation.HcabasePageDataJson &  {
        
            /**
            * Represents the Link field (3317a6f6-dbe7-4cbb-a826-605fef277ad5).
            */
            Link?: {
                jsonValue: LinkField
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/ParameterOption
    */
    export type ParameterOption = HCAProjectFoundation.BaseRenderingParameterOption &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/ParameterOption
    */
    export type ParameterOptionJson = HCAProjectFoundation.BaseRenderingParameterOptionJson &  {
        

    }
}
export namespace HCA.Project.HCA {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Partial Design Folder
    */
    export type PartialDesignFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Partial Design Folder
    */
    export type PartialDesignFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Partial Designs
    */
    export type PartialDesigns =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Partial Designs
    */
    export type PartialDesignsJson =  {
        

    }
}
export namespace Pages {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Pages/Patient Story Page
    */
    export type PatientStoryPage = HCAProjectFoundation.HcabasePage &  {
        fields?: { 
            /**
            * Represents the Date field (2a6cef4b-c5d4-4812-9996-bcbed7bbaae1).
            */
            Date?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Pages/Patient Story Page
    */
    export type PatientStoryPageJson = HCAProjectFoundation.HcabasePageJson &  {
        
            /**
            * Represents the Date field (2a6cef4b-c5d4-4812-9996-bcbed7bbaae1).
            */
            Date?: {
                jsonValue: Field<string>
            };


    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Patient stories
    */
    export type PatientStories = HCAProjectFoundation.Ctabase &  {
        fields?: { 
            /**
            * Represents the Card CTA Text field (3e825f07-23e5-4788-ad4f-f8c021369847).
            */
            CardCTAText?: Field<string>;

            /**
            * Represents the Stories field (a028bacb-1e44-4266-8d99-9859c416810b).
            */
            Stories?: Item[];

            /**
            * Represents the Text field (f0f7eafa-09d8-4f07-b552-f72923f55cc6).
            */
            Text?: Field<string>;

            /**
            * Represents the Title field (943f4079-f82e-4226-b595-2796b2aa1545).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Patient stories
    */
    export type PatientStoriesJson = HCAProjectFoundation.CtabaseJson &  {
        
            /**
            * Represents the Card CTA Text field (3e825f07-23e5-4788-ad4f-f8c021369847).
            */
            CardCTAText?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Stories field (a028bacb-1e44-4266-8d99-9859c416810b).
            */
            Stories?: {
                jsonValue: Item[]
            };

            /**
            * Represents the Text field (f0f7eafa-09d8-4f07-b552-f72923f55cc6).
            */
            Text?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (943f4079-f82e-4226-b595-2796b2aa1545).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace PageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Patient stories
    */
    export type PatientStories =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Patient stories
    */
    export type PatientStoriesJson =  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Patient stories Folder
    */
    export type PatientStoriesFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Patient stories Folder
    */
    export type PatientStoriesFolderJson =  {
        

    }
}
export namespace Foundation {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/RenderingParameterOptions Folder
    */
    export type RenderingParameterOptionsFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/RenderingParameterOptions Folder
    */
    export type RenderingParameterOptionsFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Scores
    */
    export type Scores =  {
        fields?: { 
            /**
            * Represents the Number field (2baa43f4-7140-4514-97fc-6f9638b651e7).
            */
            Number?: Field<number>;

            /**
            * Represents the Text field (2496fb09-1929-4184-a62a-36c44eba0deb).
            */
            Text?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Scores
    */
    export type ScoresJson =  {
        
            /**
            * Represents the Number field (2baa43f4-7140-4514-97fc-6f9638b651e7).
            */
            Number?: {
                jsonValue: Field<number>
            };

            /**
            * Represents the Text field (2496fb09-1929-4184-a62a-36c44eba0deb).
            */
            Text?: {
                jsonValue: Field<string>
            };


    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Service Cards
    */
    export type ServiceCards = HCAProjectFoundation.Ctabase &  {
        fields?: { 
            /**
            * Represents the Description field (164cae5b-071a-456a-be6b-7613241c9599).
            */
            Description?: Field<string>;

            /**
            * Represents the Heading field (7ee31b61-dda1-4893-8d00-3eaf1c608b7e).
            */
            Heading?: Field<string>;

            /**
            * Represents the Services field (8da1a961-cc60-4ab4-a214-19e099f6e302).
            */
            Services?: Item[];

            /**
            * Represents the Title field (c105a5a2-141b-4090-808e-fa24176aaf31).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Service Cards
    */
    export type ServiceCardsJson = HCAProjectFoundation.CtabaseJson &  {
        
            /**
            * Represents the Description field (164cae5b-071a-456a-be6b-7613241c9599).
            */
            Description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Heading field (7ee31b61-dda1-4893-8d00-3eaf1c608b7e).
            */
            Heading?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Services field (8da1a961-cc60-4ab4-a214-19e099f6e302).
            */
            Services?: {
                jsonValue: Item[]
            };

            /**
            * Represents the Title field (c105a5a2-141b-4090-808e-fa24176aaf31).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace PageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Service Cards
    */
    export type ServiceCards = HCAProjectFoundation.HeadingParameters &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Service Cards
    */
    export type ServiceCardsJson = HCAProjectFoundation.HeadingParametersJson &  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Service Cards Folder
    */
    export type ServiceCardsFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Service Cards Folder
    */
    export type ServiceCardsFolderJson =  {
        

    }
}
export namespace Pages {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Pages/Service Page
    */
    export type ServicePage = HCAProjectFoundation.HcabasePage & 
HCAProjectFoundation.Doctify.DoctifyKeywordIdMapping &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Pages/Service Page
    */
    export type ServicePageJson = HCAProjectFoundation.HcabasePageJson & 
HCAProjectFoundation.Doctify.DoctifyKeywordIdMappingJson &  {
        

    }
}
export namespace Foundation {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/ThemesParameters
    */
    export type ThemesParameters =  {
        fields?: { 
            /**
            * Represents the Theme field (ea5fdc51-8f27-47db-8fbe-e291519c5fed).
            */
            Theme?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/ThemesParameters
    */
    export type ThemesParametersJson =  {
        
            /**
            * Represents the Theme field (ea5fdc51-8f27-47db-8fbe-e291519c5fed).
            */
            Theme?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/_Abstracts
    */
    export type Abstracts =  {
        fields?: { 
            /**
            * Represents the Abstract Description field (cb5cd4c3-e70e-40de-b786-191285ba1ca3).
            */
            AbstractDescription?: Field<string>;

            /**
            * Represents the Abstract Image field (f75ec234-5a41-49cb-a275-fbb100b0c23b).
            */
            AbstractImage?: ImageField;

            /**
            * Represents the Abstract Title field (55b6773d-302d-4a16-9421-8649d41ed0d0).
            */
            AbstractTitle?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/_Abstracts
    */
    export type AbstractsJson =  {
        
            /**
            * Represents the Abstract Description field (cb5cd4c3-e70e-40de-b786-191285ba1ca3).
            */
            AbstractDescription?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Abstract Image field (f75ec234-5a41-49cb-a275-fbb100b0c23b).
            */
            AbstractImage?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Abstract Title field (55b6773d-302d-4a16-9421-8649d41ed0d0).
            */
            AbstractTitle?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/_BaseRenderingParameterOption
    */
    export type BaseRenderingParameterOption =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/_BaseRenderingParameterOption
    */
    export type BaseRenderingParameterOptionJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/_CQCBasePage
    */
    export type CqcbasePage =  {
        fields?: { 
            /**
            * Represents the Report Link field (db2959e1-65ed-409a-bad1-79700462a81d).
            */
            "Report Link"?: LinkField;

            /**
            * Represents the Status field (4d5a4bf6-6019-4639-945b-d96f40169939).
            */
            Status?: Item;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/_CQCBasePage
    */
    export type CqcbasePageJson =  {
        
            /**
            * Represents the Report Link field (db2959e1-65ed-409a-bad1-79700462a81d).
            */
            "Report Link"?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Status field (4d5a4bf6-6019-4639-945b-d96f40169939).
            */
            Status?: {
                jsonValue: Item
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/_CTABase
    */
    export type Ctabase =  {
        fields?: { 
            /**
            * Represents the CTA Icon field (dc1f5853-3482-48dc-8a23-eb4ec1115f01).
            */
            CTAIcon?: Item;

            /**
            * Represents the CTA Link field (a902abe7-6f90-452b-98d4-62a9d12d1df0).
            */
            CTALink?: LinkField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/_CTABase
    */
    export type CtabaseJson =  {
        
            /**
            * Represents the CTA Icon field (dc1f5853-3482-48dc-8a23-eb4ec1115f01).
            */
            CTAIcon?: {
                jsonValue: Item
            };

            /**
            * Represents the CTA Link field (a902abe7-6f90-452b-98d4-62a9d12d1df0).
            */
            CTALink?: {
                jsonValue: LinkField
            };


    }
}
export namespace Foundation.Doctify {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Doctify/_DoctifyKeywordIdMapping
    */
    export type DoctifyKeywordIdMapping =  {
        fields?: { 
            /**
            * Represents the Doctify KeywordId field (86550f75-4b5d-4f03-bd83-759a0bb3489b).
            */
            "Doctify KeywordId"?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Doctify/_DoctifyKeywordIdMapping
    */
    export type DoctifyKeywordIdMappingJson =  {
        
            /**
            * Represents the Doctify KeywordId field (86550f75-4b5d-4f03-bd83-759a0bb3489b).
            */
            "Doctify KeywordId"?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Doctify/_DoctifyPracticeMapping
    */
    export type DoctifyPracticeMapping =  {
        fields?: { 
            /**
            * Represents the Doctify Practice field (6572a61e-d3d4-46a0-acde-3b5b374d4ac3).
            */
            "Doctify Practice"?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Doctify/_DoctifyPracticeMapping
    */
    export type DoctifyPracticeMappingJson =  {
        
            /**
            * Represents the Doctify Practice field (6572a61e-d3d4-46a0-acde-3b5b374d4ac3).
            */
            "Doctify Practice"?: {
                jsonValue: Field<string>
            };


    }
}
export namespace Foundation {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/_HCABasePage
    */
    export type HcabasePage = HCAProjectFoundation.Navigation & 
HCAProjectFoundation.Abstracts & 
HCAProjectFoundation.HcabasePageData &  {
        fields?: { 
            /**
            * Represents the Meta Description field (a507a55f-819a-46b1-a386-a5abecad832c).
            */
            "Meta Description"?: Field<string>;

            /**
            * Represents the Meta Image field (f1a8a75b-63a0-4eda-94f2-89e152314262).
            */
            "Meta Image"?: ImageField;

            /**
            * Represents the Meta Title field (5aca086f-dae3-440f-a997-24f2cfbdd161).
            */
            "Meta Title"?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/_HCABasePage
    */
    export type HcabasePageJson = HCAProjectFoundation.NavigationJson & 
HCAProjectFoundation.AbstractsJson & 
HCAProjectFoundation.HcabasePageDataJson &  {
        
            /**
            * Represents the Meta Description field (a507a55f-819a-46b1-a386-a5abecad832c).
            */
            "Meta Description"?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Meta Image field (f1a8a75b-63a0-4eda-94f2-89e152314262).
            */
            "Meta Image"?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Meta Title field (5aca086f-dae3-440f-a997-24f2cfbdd161).
            */
            "Meta Title"?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/_HCABasePageData
    */
    export type HcabasePageData =  {
        fields?: { 
            /**
            * Represents the Description field (77332344-9643-4f3c-96fc-e015f6b423de).
            */
            Description?: Field<string>;

            /**
            * Represents the Image field (9def8dc9-3351-41a7-82c4-2c7f56f95e25).
            */
            Image?: ImageField;

            /**
            * Represents the Title field (dd6c2904-20c1-4670-b538-d523f08e60f0).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/_HCABasePageData
    */
    export type HcabasePageDataJson =  {
        
            /**
            * Represents the Description field (77332344-9643-4f3c-96fc-e015f6b423de).
            */
            Description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Image field (9def8dc9-3351-41a7-82c4-2c7f56f95e25).
            */
            Image?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Title field (dd6c2904-20c1-4670-b538-d523f08e60f0).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/_Navigation
    */
    export type Navigation =  {
        fields?: { 
            /**
            * Represents the Navigation Title field (1de420ed-ff7f-4414-bd9b-bc68934bc0e0).
            */
            "Navigation Title"?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/_Navigation
    */
    export type NavigationJson =  {
        
            /**
            * Represents the Navigation Title field (1de420ed-ff7f-4414-bd9b-bc68934bc0e0).
            */
            "Navigation Title"?: {
                jsonValue: Field<string>
            };


    }
}


