
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { Pages as HCAProjectPages } from "./HCA.Project.model"
// @ts-ignore 
import { Foundation as HCAProjectFoundation } from "./HCA.Project.model"
// @ts-ignore 
import { PageContent as HCAProjectPageContent } from "./HCA.Project.model"
// @ts-ignore 
import { HCA as HCAProjectHCA } from "./HCA.Project.model"

export namespace Pages {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Pages/Blog Page
    */
    export type BlogPage = HCAProjectFoundation.HcabasePage &  {
        fields?: { 
            /**
            * Represents the Date field (e1b9a21b-a32e-429b-bbe5-047b323fd263).
            */
            Date?: Field<string>;

            /**
            * Represents the Tags field (2fa63bb5-b5b6-4ce7-85ef-36b6b3352524).
            */
            Tags?: Item[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Pages/Blog Page
    */
    export type BlogPageJson = HCAProjectFoundation.HcabasePageJson &  {
        
            /**
            * Represents the Date field (e1b9a21b-a32e-429b-bbe5-047b323fd263).
            */
            Date?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Tags field (2fa63bb5-b5b6-4ce7-85ef-36b6b3352524).
            */
            Tags?: {
                jsonValue: Item[]
            };


    }
}
export namespace Foundation.Cqc {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/CQC/CQC
    */
    export type Cqc = HCAProjectFoundation.CqcbasePage &  {
        fields?: { 
            /**
            * Represents the StatusTest field (46b0e62d-d38b-488c-9c32-098aee5f14f0).
            */
            StatusTest?: Item;

            /**
            * Represents the Text field (fd25675b-a6f6-4fc9-be43-f7b1eed271cb).
            */
            Text?: Field<string>;

            /**
            * Represents the Title field (b5cfb002-6c07-4b59-953f-abb43486f0ce).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/CQC/CQC
    */
    export type CqcJson = HCAProjectFoundation.CqcbasePageJson &  {
        
            /**
            * Represents the StatusTest field (46b0e62d-d38b-488c-9c32-098aee5f14f0).
            */
            StatusTest?: {
                jsonValue: Item
            };

            /**
            * Represents the Text field (fd25675b-a6f6-4fc9-be43-f7b1eed271cb).
            */
            Text?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (b5cfb002-6c07-4b59-953f-abb43486f0ce).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/CQC/CQC Folder
    */
    export type CqcFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/CQC/CQC Folder
    */
    export type CqcFolderJson =  {
        

    }
}
export namespace Foundation.Settings {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Settings/CQC Settings
    */
    export type CqcSettings =  {
        fields?: { 
            /**
            * Represents the Logo field (deaa091e-8c4e-4093-ad6a-f79f00b2521a).
            */
            Logo?: ImageField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Settings/CQC Settings
    */
    export type CqcSettingsJson =  {
        
            /**
            * Represents the Logo field (deaa091e-8c4e-4093-ad6a-f79f00b2521a).
            */
            Logo?: {
                jsonValue: ImageField
            };


    }
}
export namespace Foundation.Cqc {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/CQC/CQC Status
    */
    export type CqcStatus =  {
        fields?: { 
            /**
            * Represents the CQC Logo field (cac4f9dc-c36a-4c56-97db-ebce1e7e2f29).
            */
            "CQC Logo"?: Item;

            /**
            * Represents the Icon field (f7469f76-595c-49cc-b0cc-66a5e3d33383).
            */
            Icon?: Field<string>;

            /**
            * Represents the Title field (7edb9b23-9055-4551-a6d4-edca5a3f364d).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/CQC/CQC Status
    */
    export type CqcStatusJson =  {
        
            /**
            * Represents the CQC Logo field (cac4f9dc-c36a-4c56-97db-ebce1e7e2f29).
            */
            "CQC Logo"?: {
                jsonValue: Item
            };

            /**
            * Represents the Icon field (f7469f76-595c-49cc-b0cc-66a5e3d33383).
            */
            Icon?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (7edb9b23-9055-4551-a6d4-edca5a3f364d).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/CQC/CQC Statuses Folder
    */
    export type CqcStatusesFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/CQC/CQC Statuses Folder
    */
    export type CqcStatusesFolderJson =  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/CTA Button
    */
    export type CtaButton = HCAProjectFoundation.Ctabase &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/CTA Button
    */
    export type CtaButtonJson = HCAProjectFoundation.CtabaseJson &  {
        

    }
}
export namespace PageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/CTA Button
    */
    export type CtaButton =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/CTA Button
    */
    export type CtaButtonJson =  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/CTA Button Folder
    */
    export type CtaButtonFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/CTA Button Folder
    */
    export type CtaButtonFolderJson =  {
        

    }
}
export namespace Foundation.Settings {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Settings/Custom Settings Folder
    */
    export type CustomSettingsFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Settings/Custom Settings Folder
    */
    export type CustomSettingsFolderJson =  {
        

    }
}
export namespace Foundation.Doctify {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Doctify/Doctify Filter
    */
    export type DoctifyFilter =  {
        fields?: { 
            /**
            * Represents the Filter field (51584e8c-360b-47ea-96e0-bd5d45dec2af).
            */
            Filter?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Doctify/Doctify Filter
    */
    export type DoctifyFilterJson =  {
        
            /**
            * Represents the Filter field (51584e8c-360b-47ea-96e0-bd5d45dec2af).
            */
            Filter?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Doctify/Doctify Filters
    */
    export type DoctifyFilters =  {
        fields?: { 
            /**
            * Represents the Custom Filters field (ab11cab9-17e6-42ac-98ca-aec3d7127a85).
            */
            "Custom Filters"?: Item[];

            /**
            * Represents the Practice field (d4e8f601-4189-4c53-a450-1b938d34f437).
            */
            Practice?: Item[];

            /**
            * Represents the Service field (e1dd6602-4ddc-4428-a336-986c1a3e5583).
            */
            Service?: Item[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Doctify/Doctify Filters
    */
    export type DoctifyFiltersJson =  {
        
            /**
            * Represents the Custom Filters field (ab11cab9-17e6-42ac-98ca-aec3d7127a85).
            */
            "Custom Filters"?: {
                jsonValue: Item[]
            };

            /**
            * Represents the Practice field (d4e8f601-4189-4c53-a450-1b938d34f437).
            */
            Practice?: {
                jsonValue: Item[]
            };

            /**
            * Represents the Service field (e1dd6602-4ddc-4428-a336-986c1a3e5583).
            */
            Service?: {
                jsonValue: Item[]
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Doctify/Doctify Filters Folder
    */
    export type DoctifyFiltersFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Doctify/Doctify Filters Folder
    */
    export type DoctifyFiltersFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Doctify/Doctify Reviews
    */
    export type DoctifyReviews =  {
        fields?: { 
            /**
            * Represents the Reviews field (ef0cf15c-3c69-4958-9cc1-e71ad136219d).
            */
            Reviews?: Field<string>;

            /**
            * Represents the Stars field (8768d68c-852a-48ad-98d6-f5b0ddac4fbd).
            */
            Stars?: Field<number>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Doctify/Doctify Reviews
    */
    export type DoctifyReviewsJson =  {
        
            /**
            * Represents the Reviews field (ef0cf15c-3c69-4958-9cc1-e71ad136219d).
            */
            Reviews?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Stars field (8768d68c-852a-48ad-98d6-f5b0ddac4fbd).
            */
            Stars?: {
                jsonValue: Field<number>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Doctify/Doctify Reviews Folder
    */
    export type DoctifyReviewsFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Doctify/Doctify Reviews Folder
    */
    export type DoctifyReviewsFolderJson =  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Doctor cards
    */
    export type DoctorCards = HCAProjectFoundation.Doctify.DoctifyFilters & 
HCAProjectFoundation.Ctabase &  {
        fields?: { 
            /**
            * Represents the CTA Card field (5a674cd7-c9eb-4be4-8577-5c3d6d72c70c).
            */
            "CTA Card"?: LinkField;

            /**
            * Represents the Number of Cards field (f75ab386-350c-44ca-97a1-3b63a8a61cdc).
            */
            "Number of Cards"?: Field<number>;

            /**
            * Represents the Title field (fd86c684-2a05-4705-8d10-4eb1bc9156f5).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Doctor cards
    */
    export type DoctorCardsJson = HCAProjectFoundation.Doctify.DoctifyFiltersJson & 
HCAProjectFoundation.CtabaseJson &  {
        
            /**
            * Represents the CTA Card field (5a674cd7-c9eb-4be4-8577-5c3d6d72c70c).
            */
            "CTA Card"?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Number of Cards field (f75ab386-350c-44ca-97a1-3b63a8a61cdc).
            */
            "Number of Cards"?: {
                jsonValue: Field<number>
            };

            /**
            * Represents the Title field (fd86c684-2a05-4705-8d10-4eb1bc9156f5).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace PageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Doctor cards
    */
    export type DoctorCards = HCAProjectFoundation.HeadingParameters &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Doctor cards
    */
    export type DoctorCardsJson = HCAProjectFoundation.HeadingParametersJson &  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Doctor cards Folder
    */
    export type DoctorCardsFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Doctor cards Folder
    */
    export type DoctorCardsFolderJson =  {
        

    }
}
export namespace Foundation {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/HCAIcon
    */
    export type Hcaicon =  {
        fields?: { 
            /**
            * Represents the SVG Markup field (f42617c7-46b7-46f3-a075-69ebf514838e).
            */
            "SVG Markup"?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/HCAIcon
    */
    export type HcaiconJson =  {
        
            /**
            * Represents the SVG Markup field (f42617c7-46b7-46f3-a075-69ebf514838e).
            */
            "SVG Markup"?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/HeadingParameters
    */
    export type HeadingParameters =  {
        fields?: { 
            /**
            * Represents the Heading Size field (b791330d-3cf2-4c11-a07f-5a29d392c972).
            */
            "Heading Size"?: Field<string>;

            /**
            * Represents the Heading Tag field (be0ce91d-874a-4f9c-8418-6c173f5593af).
            */
            "Heading Tag"?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/HeadingParameters
    */
    export type HeadingParametersJson =  {
        
            /**
            * Represents the Heading Size field (b791330d-3cf2-4c11-a07f-5a29d392c972).
            */
            "Heading Size"?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Heading Tag field (be0ce91d-874a-4f9c-8418-6c173f5593af).
            */
            "Heading Tag"?: {
                jsonValue: Field<string>
            };


    }
}
export namespace HCA.Project.HCA {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Headless Site
    */
    export type HeadlessSite =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Headless Site
    */
    export type HeadlessSiteJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Headless Tenant
    */
    export type HeadlessTenant =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Headless Tenant
    */
    export type HeadlessTenantJson =  {
        

    }
}
export namespace Foundation {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Icons Folder
    */
    export type IconsFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Icons Folder
    */
    export type IconsFolderJson =  {
        

    }
}
export namespace HCA.Project.HCA {

    /**
    * Represents the template /sitecore/templates/Project/HCA/JSS Settings
    */
    export type JssSettings =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/JSS Settings
    */
    export type JssSettingsJson =  {
        

    }
}
export namespace Pages {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Pages/Location Page
    */
    export type LocationPage = HCAProjectFoundation.HcabasePage & 
HCAProjectFoundation.Doctify.DoctifyPracticeMapping &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Pages/Location Page
    */
    export type LocationPageJson = HCAProjectFoundation.HcabasePageJson & 
HCAProjectFoundation.Doctify.DoctifyPracticeMappingJson &  {
        

    }
}
export namespace HCA.Project.HCA {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page
    */
    export type Page =  {
        fields?: { 
            /**
            * Represents the Content field (38b0e5ab-0239-472e-8605-a55987ae3f43).
            */
            Content?: Field<string>;

            /**
            * Represents the Title field (f253d55f-c5e7-4bbd-8423-45ee6c8a12ec).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page
    */
    export type PageJson =  {
        
            /**
            * Represents the Content field (38b0e5ab-0239-472e-8605-a55987ae3f43).
            */
            Content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (f253d55f-c5e7-4bbd-8423-45ee6c8a12ec).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Design Folder
    */
    export type PageDesignFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Design Folder
    */
    export type PageDesignFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Designs
    */
    export type PageDesigns =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Designs
    */
    export type PageDesignsJson =  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Page Proxy
    */
    export type PageProxy = HCAProjectFoundation.HcabasePageData &  {
        fields?: { 
            /**
            * Represents the Link field (1b699dd6-99de-4058-a91d-f3fd23b47e41).
            */
            Link?: LinkField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Page Proxy
    */
    export type PageProxyJson = HCAProjectFoundation.HcabasePageDataJson &  {
        
            /**
            * Represents the Link field (1b699dd6-99de-4058-a91d-f3fd23b47e41).
            */
            Link?: {
                jsonValue: LinkField
            };


    }
}
export namespace Foundation {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Page Proxy
    */
    export type PageProxy = HCAProjectFoundation.HcabasePageData &  {
        fields?: { 
            /**
            * Represents the Link field (3317a6f6-dbe7-4cbb-a826-605fef277ad5).
            */
            Link?: LinkField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Page Proxy
    */
    export type PageProxyJson = HCAProjectFoundation.HcabasePageDataJson &  {
        
            /**
            * Represents the Link field (3317a6f6-dbe7-4cbb-a826-605fef277ad5).
            */
            Link?: {
                jsonValue: LinkField
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/ParameterOption
    */
    export type ParameterOption = HCAProjectFoundation.BaseRenderingParameterOption &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/ParameterOption
    */
    export type ParameterOptionJson = HCAProjectFoundation.BaseRenderingParameterOptionJson &  {
        

    }
}
export namespace HCA.Project.HCA {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Partial Design Folder
    */
    export type PartialDesignFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Partial Design Folder
    */
    export type PartialDesignFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Partial Designs
    */
    export type PartialDesigns =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Partial Designs
    */
    export type PartialDesignsJson =  {
        

    }
}
export namespace Pages {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Pages/Patient Story Page
    */
    export type PatientStoryPage = HCAProjectFoundation.HcabasePage &  {
        fields?: { 
            /**
            * Represents the Date field (2a6cef4b-c5d4-4812-9996-bcbed7bbaae1).
            */
            Date?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Pages/Patient Story Page
    */
    export type PatientStoryPageJson = HCAProjectFoundation.HcabasePageJson &  {
        
            /**
            * Represents the Date field (2a6cef4b-c5d4-4812-9996-bcbed7bbaae1).
            */
            Date?: {
                jsonValue: Field<string>
            };


    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Patient stories
    */
    export type PatientStories = HCAProjectFoundation.Ctabase &  {
        fields?: { 
            /**
            * Represents the Card CTA Text field (3e825f07-23e5-4788-ad4f-f8c021369847).
            */
            "Card CTA Text"?: Field<string>;

            /**
            * Represents the Stories field (a028bacb-1e44-4266-8d99-9859c416810b).
            */
            Stories?: Item[];

            /**
            * Represents the Text field (f0f7eafa-09d8-4f07-b552-f72923f55cc6).
            */
            Text?: Field<string>;

            /**
            * Represents the Title field (943f4079-f82e-4226-b595-2796b2aa1545).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Patient stories
    */
    export type PatientStoriesJson = HCAProjectFoundation.CtabaseJson &  {
        
            /**
            * Represents the Card CTA Text field (3e825f07-23e5-4788-ad4f-f8c021369847).
            */
            "Card CTA Text"?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Stories field (a028bacb-1e44-4266-8d99-9859c416810b).
            */
            Stories?: {
                jsonValue: Item[]
            };

            /**
            * Represents the Text field (f0f7eafa-09d8-4f07-b552-f72923f55cc6).
            */
            Text?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (943f4079-f82e-4226-b595-2796b2aa1545).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace PageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Patient stories
    */
    export type PatientStories =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Patient stories
    */
    export type PatientStoriesJson =  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Patient stories Folder
    */
    export type PatientStoriesFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Patient stories Folder
    */
    export type PatientStoriesFolderJson =  {
        

    }
}
export namespace Foundation {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/RenderingParameterOptions Folder
    */
    export type RenderingParameterOptionsFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/RenderingParameterOptions Folder
    */
    export type RenderingParameterOptionsFolderJson =  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Service Cards
    */
    export type ServiceCards = HCAProjectFoundation.Ctabase &  {
        fields?: { 
            /**
            * Represents the Description field (164cae5b-071a-456a-be6b-7613241c9599).
            */
            Description?: Field<string>;

            /**
            * Represents the Heading field (7ee31b61-dda1-4893-8d00-3eaf1c608b7e).
            */
            Heading?: Field<string>;

            /**
            * Represents the Services field (8da1a961-cc60-4ab4-a214-19e099f6e302).
            */
            Services?: Item[];

            /**
            * Represents the Title field (c105a5a2-141b-4090-808e-fa24176aaf31).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Service Cards
    */
    export type ServiceCardsJson = HCAProjectFoundation.CtabaseJson &  {
        
            /**
            * Represents the Description field (164cae5b-071a-456a-be6b-7613241c9599).
            */
            Description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Heading field (7ee31b61-dda1-4893-8d00-3eaf1c608b7e).
            */
            Heading?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Services field (8da1a961-cc60-4ab4-a214-19e099f6e302).
            */
            Services?: {
                jsonValue: Item[]
            };

            /**
            * Represents the Title field (c105a5a2-141b-4090-808e-fa24176aaf31).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace PageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Service Cards
    */
    export type ServiceCards = HCAProjectFoundation.HeadingParameters &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Rendering Parameters/Service Cards
    */
    export type ServiceCardsJson = HCAProjectFoundation.HeadingParametersJson &  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Page Content/Service Cards Folder
    */
    export type ServiceCardsFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Page Content/Service Cards Folder
    */
    export type ServiceCardsFolderJson =  {
        

    }
}
export namespace Pages {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Pages/Service Page
    */
    export type ServicePage = HCAProjectFoundation.HcabasePage & 
HCAProjectFoundation.Doctify.DoctifyKeywordIdMapping &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Pages/Service Page
    */
    export type ServicePageJson = HCAProjectFoundation.HcabasePageJson & 
HCAProjectFoundation.Doctify.DoctifyKeywordIdMappingJson &  {
        

    }
}
export namespace Foundation {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/_Abstracts
    */
    export type Abstracts =  {
        fields?: { 
            /**
            * Represents the Abstract Description field (cb5cd4c3-e70e-40de-b786-191285ba1ca3).
            */
            "Abstract Description"?: Field<string>;

            /**
            * Represents the Abstract Image field (f75ec234-5a41-49cb-a275-fbb100b0c23b).
            */
            "Abstract Image"?: ImageField;

            /**
            * Represents the Abstract Title field (55b6773d-302d-4a16-9421-8649d41ed0d0).
            */
            "Abstract Title"?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/_Abstracts
    */
    export type AbstractsJson =  {
        
            /**
            * Represents the Abstract Description field (cb5cd4c3-e70e-40de-b786-191285ba1ca3).
            */
            "Abstract Description"?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Abstract Image field (f75ec234-5a41-49cb-a275-fbb100b0c23b).
            */
            "Abstract Image"?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Abstract Title field (55b6773d-302d-4a16-9421-8649d41ed0d0).
            */
            "Abstract Title"?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/_BaseRenderingParameterOption
    */
    export type BaseRenderingParameterOption =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/_BaseRenderingParameterOption
    */
    export type BaseRenderingParameterOptionJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/_CQCBasePage
    */
    export type CqcbasePage =  {
        fields?: { 
            /**
            * Represents the Report Link field (db2959e1-65ed-409a-bad1-79700462a81d).
            */
            "Report Link"?: LinkField;

            /**
            * Represents the Status field (4d5a4bf6-6019-4639-945b-d96f40169939).
            */
            Status?: Item;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/_CQCBasePage
    */
    export type CqcbasePageJson =  {
        
            /**
            * Represents the Report Link field (db2959e1-65ed-409a-bad1-79700462a81d).
            */
            "Report Link"?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Status field (4d5a4bf6-6019-4639-945b-d96f40169939).
            */
            Status?: {
                jsonValue: Item
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/_CTABase
    */
    export type Ctabase =  {
        fields?: { 
            /**
            * Represents the CTA Link field (a902abe7-6f90-452b-98d4-62a9d12d1df0).
            */
            "CTA Link"?: LinkField;

            /**
            * Represents the Icon field (dc1f5853-3482-48dc-8a23-eb4ec1115f01).
            */
            Icon?: Item;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/_CTABase
    */
    export type CtabaseJson =  {
        
            /**
            * Represents the CTA Link field (a902abe7-6f90-452b-98d4-62a9d12d1df0).
            */
            "CTA Link"?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Icon field (dc1f5853-3482-48dc-8a23-eb4ec1115f01).
            */
            Icon?: {
                jsonValue: Item
            };


    }
}
export namespace Foundation.Doctify {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Doctify/_DoctifyKeywordIdMapping
    */
    export type DoctifyKeywordIdMapping =  {
        fields?: { 
            /**
            * Represents the Doctify KeywordId field (86550f75-4b5d-4f03-bd83-759a0bb3489b).
            */
            "Doctify KeywordId"?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Doctify/_DoctifyKeywordIdMapping
    */
    export type DoctifyKeywordIdMappingJson =  {
        
            /**
            * Represents the Doctify KeywordId field (86550f75-4b5d-4f03-bd83-759a0bb3489b).
            */
            "Doctify KeywordId"?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/Doctify/_DoctifyPracticeMapping
    */
    export type DoctifyPracticeMapping =  {
        fields?: { 
            /**
            * Represents the Doctify Practice field (6572a61e-d3d4-46a0-acde-3b5b374d4ac3).
            */
            "Doctify Practice"?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/Doctify/_DoctifyPracticeMapping
    */
    export type DoctifyPracticeMappingJson =  {
        
            /**
            * Represents the Doctify Practice field (6572a61e-d3d4-46a0-acde-3b5b374d4ac3).
            */
            "Doctify Practice"?: {
                jsonValue: Field<string>
            };


    }
}
export namespace Foundation {

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/_HCABasePage
    */
    export type HcabasePage = HCAProjectFoundation.Navigation & 
HCAProjectFoundation.Abstracts & 
HCAProjectFoundation.HcabasePageData &  {
        fields?: { 
            /**
            * Represents the Meta Description field (a507a55f-819a-46b1-a386-a5abecad832c).
            */
            "Meta Description"?: Field<string>;

            /**
            * Represents the Meta Image field (f1a8a75b-63a0-4eda-94f2-89e152314262).
            */
            "Meta Image"?: ImageField;

            /**
            * Represents the Meta Title field (5aca086f-dae3-440f-a997-24f2cfbdd161).
            */
            "Meta Title"?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/_HCABasePage
    */
    export type HcabasePageJson = HCAProjectFoundation.NavigationJson & 
HCAProjectFoundation.AbstractsJson & 
HCAProjectFoundation.HcabasePageDataJson &  {
        
            /**
            * Represents the Meta Description field (a507a55f-819a-46b1-a386-a5abecad832c).
            */
            "Meta Description"?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Meta Image field (f1a8a75b-63a0-4eda-94f2-89e152314262).
            */
            "Meta Image"?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Meta Title field (5aca086f-dae3-440f-a997-24f2cfbdd161).
            */
            "Meta Title"?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/_HCABasePageData
    */
    export type HcabasePageData =  {
        fields?: { 
            /**
            * Represents the Description field (77332344-9643-4f3c-96fc-e015f6b423de).
            */
            Description?: Field<string>;

            /**
            * Represents the Image field (9def8dc9-3351-41a7-82c4-2c7f56f95e25).
            */
            Image?: ImageField;

            /**
            * Represents the Title field (dd6c2904-20c1-4670-b538-d523f08e60f0).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/_HCABasePageData
    */
    export type HcabasePageDataJson =  {
        
            /**
            * Represents the Description field (77332344-9643-4f3c-96fc-e015f6b423de).
            */
            Description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Image field (9def8dc9-3351-41a7-82c4-2c7f56f95e25).
            */
            Image?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Title field (dd6c2904-20c1-4670-b538-d523f08e60f0).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HCA/Foundation/_Navigation
    */
    export type Navigation =  {
        fields?: { 
            /**
            * Represents the Navigation Title field (1de420ed-ff7f-4414-bd9b-bc68934bc0e0).
            */
            "Navigation Title"?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HCA/Foundation/_Navigation
    */
    export type NavigationJson =  {
        
            /**
            * Represents the Navigation Title field (1de420ed-ff7f-4414-bd9b-bc68934bc0e0).
            */
            "Navigation Title"?: {
                jsonValue: Field<string>
            };


    }
}


