---
ID: "2e22e8bd-34c9-4111-9d34-59c29cc43a97"
Parent: "b77dfb7a-e9cb-48d5-a5fc-88adc680b3f5"
Template: "b77dfb7a-e9cb-48d5-a5fc-88adc680b3f5"
Path: /sitecore/templates/Project/HCA/Foundation/Location Proxy/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "10f7bc8e-4d4c-476b-b326-8dfe66904a7b"
      Hint: Title
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260421T182201Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "65a0189e-e2a9-46c5-b232-45ee53abcf0d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bartek.glomski@eqtr.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260421T182207Z
