//function is intended to extract named params from props?.params?.styles string.
//string generated by xmc and based on styles selected for each rendering.
//avaialble styles are defined under /sitecore/content/HCA/HCA-Main/Presentation/Styles
//named param in styles collection should look like: "textwidth__narrow"

export function getPresentationParam(
  params: string | undefined | null,
  paramName: string
): string | undefined {
  if (!params) return undefined;

  const prefix = `${paramName}__`;

  return params
    .split(/\s+/)
    .find((p) => p.startsWith(prefix))
    ?.slice(prefix.length);
}
