# enables storybook-publisher once per day, to apply a daily limit to Chromatic builds
name: Enable workflow
on:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  enable-workflow:
    runs-on: ubuntu-latest
    steps:
    - run: gh workflow enable "Storybook Publisher"
      env:
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}